### ISSUE TITLE
Implement backend part of Log Search feature

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1001]
The issue is to provide HTTP API which queries to Ambari Infra (Solr) with some criteria, and provide query results to the UI. UI will construct frontend of log search feature based on the API.

This assumes Storm worker log is parsed as pre-defined schema, and published to Ambari Infra. We will take care of this from Ambari side.

**Comment by HeartSaVioR** [comment]
#1002 for the first cut of PR.

**Comment by shahsank3t** [comment]
Filed a separate issue to implement UI for this one: https://github.com/hortonworks/streamline/issues/1033
