### ISSUE TITLE
Support windowing on Event Time in Join processor backend.

### ISSUE THREAD

**Issue by roshannaik** [hortonworks/streamline#1003]

**Comment by roshannaik** [comment]
PR: https://github.com/hortonworks/streamline/pull/1004

**Comment by roshannaik** [comment]
Was able to test this in Test mode.  Given the issue with Kafka spout was unable to test with it.

**Comment by arunmahadevan** [comment]
The issue with kafka was env config issue. probably we should add some checks in Ambari to prevent invalid configs. Will raise an issue with that

**Comment by arunmahadevan** [comment]
Addressed via https://github.com/hortonworks/streamline/pull/1004
