### ISSUE TITLE
Highlight source which emits selected root event in test event correlation result

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1008]
We've added event correlation in test mode via ISSUE-964.

For simple topology the result is intuitive, but there're some cases that multiple root events are shown in one or more sources when topology has either aggregation processor or join processor which makes confusion which event is the origin event to track.

This issue is to highlight source which emits selected root event in test event correlation result, and also selected root event as well.

**Comment by HeartSaVioR** [comment]
#1009 

@shahsank3t Given that this issue needs UI integration, please label UI and assign as well. Thanks!

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/1011
