### ISSUE TITLE
Dynamically changing log level at Application level

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1014]
Storm has the feature of `Dynamic Log Level Settings`, which enables users to change log level of Loggers in specific package (and sub package/classes).

We would like to provide the same feature as well, but allowing only Application level cause the runtime class of SAM component may be not unique across components in Application.

**Comment by HeartSaVioR** [comment]
#1016

**Comment by arunmahadevan** [comment]
thanks @HeartSaVioR , merged #1016 to master.
