### ISSUE TITLE
Bumpup registry version to 0.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by satishd** [hortonworks/streamline#1021]

**Comment by HeartSaVioR** [comment]
Could we switch the dependency of Registry to non-SNAPSHOT version? I guess we've planned to release new Registry version soon, and then Streamline should be able to run with official version of Registry. I wish Streamline could treat Registry just as major dependency, not sibling of projects.

**Comment by satishd** [comment]
We may have a feature which streamline wants to use, there may be changes happening on that feature in snapshots and streamline wants to consume those changes. This case occurs frequently like feature of transactions support in storage layer. 
It may not be possible to have maint releases as dependent project needs some changes. 

Are we having any release plans of streamline unrelated to HDF releases? That may need to be fixed.

**Comment by HeartSaVioR** [comment]
That makes sense for dealing with common layer (so OK to rely on 0.4-SNAPSHOT), but normally not strictly needed if we release Registry more frequently. I don't know we have plan to release Streamline independently, but as you said, referring SNAPSHOT version of dependency would block Streamline to be released.

**Comment by satishd** [comment]
Registry can not be released as and when streamline needs some set of changes. So, it should be maintained in the same way as storm/kafka or any other open source projects for streamline.

**Comment by arunmahadevan** [comment]
Can we push the registry SNAPSHOT version to maven periodically and whenever there are any new dependencies ? that might address some of the issues.

**Comment by arunmahadevan** [comment]
Merged https://github.com/hortonworks/streamline/pull/1022 to master
