### ISSUE TITLE
Group test mode events in the bottom nav bar

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1026]
Right now the individual root events are displayed in the bottom bar. This is not a very intuitive way for users to navigate the events because the same set of events can repeat at the sources.

1. Add an API to return group of related events
2. UI displays the bottom panel based on the groups of events.

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/1034

**Comment by HeartSaVioR** [comment]
Closing as #1034 has been merged.
