### ISSUE TITLE
Implement UI part of Log Search feature

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#1033]
Based on API response from https://github.com/hortonworks/streamline/pull/1002, UI can provide following functionalities:
1. Log Table Listing + Pagination
2. Filter on multiple components
3. Filter on multiple log levels
4. Search for logs
5. Add date-time picker to select `from` and `to` date-time to fetch logs.

**Comment by satishwaghela** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/1037

**Comment by arunmahadevan** [comment]
Thanks for addressing this issue and providing the patch. Merged #1037 to master
