### ISSUE TITLE
Allow user to select nested fields in Druid Sink UI

### ISSUE THREAD

**Issue by omkreddy** [hortonworks/streamline#1046]
we need to flatten the nested fields and show all of them in the drop-down. 
We need to follow below pattern. Fields should be separated with "." 

field1
field2.nestedfield1
field2.nestedfield2
field2.nestedfield3
field3.nestedfield1.nestedfield2

**Comment by satishwaghela** [comment]
@omkreddy 
This implementation is like if "noNestedFields" is not there in [hint](https://github.com/hortonworks/streamline/blob/master/bootstrap/components/sinks/v001__druid-sink-topology-component.json#L89) then we will show all the nested fields right?

**Comment by omkreddy** [comment]
@satishwaghela  yes.. also we can remove noNestedFields hint for the druid-sink  definition.

**Comment by satishwaghela** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/1059

**Comment by arunmahadevan** [comment]
Merged #1059 to master
