### ISSUE TITLE
Aggregate processor emits event with anchoring all the input events in same window

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1048]
Currently, aggregate processor emits event with anchoring all the input events in same window, which brings unrelated events shown as correlated in test mode event correlation.

In other words, aggregate processor works like group-by so if there're some events like (A, 1), (A, 2), (B, 3), (B, 4), (C, 5) and aggregate processor calculates sum, it will emit (A, 3), (B, 7), (C, 5).
(A, 3) is correlated to only (A, 1), (A, 2), and (B, 7) is correlated to only (B, 3), (B, 4), and so on, but current aggregate processor correlates (A, 3), (B, 7), (C, 5) to all the input events.

We should anchor only related events while emitting new events, say anchor (A, 1) and (A, 2) for (A, 3).

**Comment by roshannaik** [comment]
Yes. Makes sense. Each output tuple should be anchored only to its respective input tuples.
-roshan

**Comment by HeartSaVioR** [comment]
#1051

**Comment by arunmahadevan** [comment]
Thanks @HeartSaVioR for addressing this. Merged #1051 to master.
