### ISSUE TITLE
Fix behaviour of selecting nested fields in Join processor

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#1049]
Currently, if a user selects a nested field as output field in join processor, UI shows that field as a parent field and on selecting the parent (of nested field), previously selected nested field is removed and all fields (parent + it's nested field) are selected.

As per discussion with @roshannaik , we need to keep previously selected nested field as well as newly selected parent field (with all its nested fields).

Example:
`ParentField:{innerField, innerField2, innerField3}`

On selecting `innerField2`, UI should show that field (Already implemented)

Then on selecting `ParentField`, UI should show `innerField2` as well as `ParentField:{innerField, innerField2, innerField3}` into the output stream.

**Comment by sameer79** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/1060
