### ISSUE TITLE
Streamline doesn't work properly if installed path contains one of (test/src/javadoc/runtime-storm)

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1057]
https://github.com/hortonworks/streamline/blob/734d96276d1e1d9d005c9d9e4150b0966c8b0e43/bin/streamline-server-start.sh#L54-L73

It should check with only file name, but it doesn't, hence whenever the path contains one of (test/src/javadoc/runtime), no jar will be added to classpath and Streamline fails to run.

**Comment by arunmahadevan** [comment]
Fixed in https://github.com/hortonworks/streamline/pull/1058
