### ISSUE TITLE
Disable the logsearch button in UI if Logsearch and Ambari Infra is not available in the Environment

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1071]
We need to hide the logsearch button in view mode if the SAM Env does not have Ambari infra.

We cannot guarantee that the cluster will have Ambari Infra and logsearch especially when the user has already installed SAM and upgrades to HDF 3.1.

**Comment by arunmahadevan** [comment]
@shahsank3t @HeartSaVioR , do we need any backend APIs for this or the UI can figure it out ?

**Comment by shahsank3t** [comment]
Basically, if the user selects Ambari Infra while creating an environment and uses the same one to create an application, we should show LogSearch button else not. 
I'll make the required changes.

@arunmahadevan No backend API's or changes should be needed for this change.

**Comment by shahsank3t** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/1073

**Comment by arunmahadevan** [comment]
Merged to master
