### ISSUE TITLE
Right click actions on component in view mode.

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1088]
- Actions on clicking (or right clicking) component
    1. turn on logging
        Backend needs to provide API. This TBD.
    2. turn on sampling
        We have the backend API for component level sampling, so this can be achieved.
    3. A link “Go to log search" and preselect the component in the log search UI.

**Comment by sameer79** [comment]
This fix in https://github.com/hortonworks/streamline/pull/1101
