### ISSUE TITLE
UI changes to display and search sampled events

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1097]
The user should be able to enable sampling at topology and component level.

Then they should be able to search through the sampled events (UI similar to logsearch).

Backend API - https://github.com/hortonworks/streamline/pull/1096
And https://github.com/hortonworks/streamline/pull/1031 (except the API to fetch the events).

**Comment by sameer79** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/1101
