### ISSUE TITLE
Sampling status API responds HTTP 404 when topology is not running

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1102]
Quoting Arun Iyer's comment in https://github.com/hortonworks/streamline/pull/1101#issuecomment-352861856:

> If the topology is not deployed, I see some 404 pop ups in the view mode. We appear to be issuing requests to the sampling APIs and throwing it back in the UI.
> maybe the API should return empty results if it cant find the component from Storm (since the topology is not yet deployed).

**Comment by arunmahadevan** [comment]
Thanks @HeartSaVioR , merged #1103 to master
