### ISSUE TITLE
UI issues in view mode

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1107]
1. After entering sampling pct at topology level the message displayed is "Sampling enable successfully". We can change it to "Sampling enabled successfully" or just "Sampling enabled". Similarly for component level it could be "Component sampling enabled". Similar text changes for disabling.

2. For topology level, the sampling setting takes effect once the mouse is clicked outside the settings box. However for component level I need to hit return key. We could have similar behavior for both settings.

3. While changing the log level also the "Sampling enable successfully" message is displayed.

**Comment by HeartSaVioR** [comment]
3. in case of confusion, please change the message accordingly like "Changing log level successfully"

**Comment by sameer79** [comment]
Raised  PR : https://github.com/hortonworks/streamline/pull/1111

**Comment by shahsank3t** [comment]
#1111 is closed.
Raised another PR to address this issue: https://github.com/hortonworks/streamline/pull/1114

**Comment by arunmahadevan** [comment]
Merged #1114 to master
