### ISSUE TITLE
View mode metrics changes

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1108]
Based on PM feedback we need to show

1. End-end latency in the sources. Sources are already capturing end-end latency. So for sources alone, we can rename the label from "Latency" to "Overall Latency" or "Latency (end-end)" to be more clear.

2. The bottom panel for Sources shows "Process Time" which is always 0. Does it actually capture anything? If not we can remove it. Also rename the "Latency" -> "Overall Latency" or "Latency (end-end)" for Sources.

3. Execute latency in the processors and sinks components. Right now it shows process latency which includes the time to ACK so does not capture the actual time it spends in the execute. (I am referring to execute and process latency based on the Storm).

   Execute latency: The average time a Tuple spends in the execute method. The execute method may complete without sending an Ack for the tuple.

   Process latency: The average time it takes to Ack a Tuple after it is first received.  Bolts that join, aggregate or batch may not Ack a tuple until a number of other Tuples have been received.

4. We can show the execute latency and process latency in component overview and in the bottom panel for processors and sinks.

**Comment by HeartSaVioR** [comment]
We should remove "process time" in source since neither Storm nor Streamline support it.

Both execute time and process time need to be shown in processor/sink box too, because neither one can always represent the right latency. (Sometimes process time is closer, sometimes in opposite)

Let's remove "Process Time" in All Components in the bottom panel. It doesn't give any meaningful values (it's just an average aggregation of "process time" on all components.)

**Comment by HeartSaVioR** [comment]
I'll update the metric API to provide execute time in response (will be added to misc part, since it is only matched to Storm)

**Comment by HeartSaVioR** [comment]
Filed #1109 for adding execute time in response. Please note that "latency" in summary is still referring "process time" for processors/sinks and "complete latency" for sources.

**Comment by arunmahadevan** [comment]
@shahsank3t , can you take care of the UI side changes for this ? For the UI changes that depends of the backend API changes you can wait until #1109 is merged.

**Comment by shahsank3t** [comment]
@arunmahadevan @HeartSaVioR 

>1. End-end latency in the sources. Sources are already capturing end-end latency. So for sources alone, we can rename the label from "Latency" to "Overall Latency" or "Latency (end-end)" to be more clear.

Do we need to rename "Latency" in the component box itself or in the below panel showing metric values (not the graph)?

>2. The bottom panel for Sources shows "Process Time" which is always 0. Does it actually capture anything? If not we can remove it. Also rename the "Latency" -> "Overall Latency" or "Latency (end-end)" for Sources.

Removed "Process Time" and renamed "Latency" to "Overall Latency" in the bottom panel for the source.
![image](https://user-images.githubusercontent.com/6761317/34317255-b3191aae-e7d0-11e7-97b8-3c77f8626d9d.png)

> 3. Execute latency in the processors and sinks components. Right now it shows process latency which includes the time to ACK so does not capture the actual time it spends in the execute. (I am referring to execute and process latency based on the Storm).
> 
> Execute latency: The average time a Tuple spends in the execute method. The execute method may complete without sending an Ack for the tuple.
> 
> Process latency: The average time it takes to Ack a Tuple after it is first received. Bolts that join, aggregate or batch may not Ack a tuple until a number of other Tuples have been received.
 

Added "Execute Time" graph for processors and sinks in the bottom panel metrics.
![image](https://user-images.githubusercontent.com/6761317/34317274-02067df0-e7d1-11e7-8212-0f70cd5c0a3b.png)

>4. We can show the execute latency and process latency in the component overview and in the bottom panel for processors and sinks.

Once the execute latency is whitelisted from Ambari and our API starts providing the response, I'll make the UI change to rename and add execute/process time in the component box as well as the bottom panel.

Just to summarize: Will create a PR for points 2 & 3, need clarification on point 1 and holding changes for point 4.

**Comment by shahsank3t** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/1113

**Comment by arunmahadevan** [comment]
@shahsank3t , commented here https://github.com/hortonworks/streamline/pull/1113#issuecomment-353733898

**Comment by arunmahadevan** [comment]
@shahsank3t , thanks for taking care of this. Merged #1113 to master.
