### ISSUE TITLE
Environment gets updated even without making any changes in edit page and clicking on save

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#1148]
Steps to reproduce:
1. Add an environment containing HBase & HDFS or Hive & HDFS and save it.
2. Edit the same environment but without any changes, click on save.
Result: HDFS gets removed from the environment.
Redo the same 2nd step now and HDFS gets added again.

UI is not sending the data correctly by editing the environment.

**Comment by arunmahadevan** [comment]
Merged https://github.com/hortonworks/streamline/pull/1149 to master
