### ISSUE TITLE
Support Kafka metrics in SAM

### ISSUE THREAD

**Issue by omkreddy** [hortonworks/streamline#1168]
We want to be able to display Kafka spout related metrics in SAM view mode.
SAM has api to return the kafka topic offsets and for HDF 3.1 we could just use that.
https://github.com/hortonworks/streamline/blob/master/streams/service/src/main/java/com/hortonworks/streamline/streams/service/MetricsResource.java#L209

cc  @shahsank3t

**Comment by sameer79** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/1203

**Comment by arunmahadevan** [comment]
Thanks @sameer79 , merged to master.
