### ISSUE TITLE
Limit input stream to sink with single streams

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#1170]
1. Currently, multiple streams are allowed to get connected to sinks which are not supported by the backend. Need to limit that to a single stream for all sinks.
2. For following sinks => fields, while saving the sinks, replace `streamID:fieldName` format with `fieldName`:

> Druid => dimensions
> HDFS => outputFields
> HIVE => fields & partitionFields
> JDBC => columns

cc: @satishd @arunmahadevan @omkreddy

**Comment by sameer79** [comment]
PR Raised https://github.com/hortonworks/streamline/pull/1171
