### ISSUE TITLE
The view mode DAG metrics values flow out of the box

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1176]
Based on the number thats being displayed, sometimes the values flow out of the box.

<img width="661" alt="screen shot 2018-01-18 at 10 05 23 am" src="https://user-images.githubusercontent.com/6792890/35113763-7df5d22e-fc37-11e7-99f0-d6ae1e524f15.png">

Is it possible to resize automatically ? If you see the screenshot, the sink looks fine and slightly wider to accomodate the values compared to the source.

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/1183

**Comment by arunmahadevan** [comment]
Thanks @sameer79 for the patch.
