### ISSUE TITLE
View mode - metrics view does not display all the values

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1177]
See the attached screenshot.

<img width="1024" alt="screen shot 2018-01-18 at 10 59 09 am" src="https://user-images.githubusercontent.com/6792890/35116018-d28b7968-fc3e-11e7-8036-e5e4bb63979f.png">

Some values are cut off near the bottom of the box and not able to view the values. It may be better to allow user to resize the box.

**Comment by shahsank3t** [comment]
@arunmahadevan 
You can scroll inside the component and check the values/graph. Let me know if it doesn't work for you.

**Comment by sameer79** [comment]
@arunmahadevan  @shahsank3t content scrollable was not added to view mode metrics. Fix in below PR.
Raised PR : https://github.com/hortonworks/streamline/pull/1185

**Comment by shahsank3t** [comment]
Thanks @sameer79 we might have missed it before while testing.

**Comment by arunmahadevan** [comment]
Thanks @sameer79 for the patch.
