### ISSUE TITLE
Log search results UI issues

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1205]
1. Log search always displays the oldest results for the selected intervals. There is no way to sort it to see the latest ones first.

2. Displays only levels >= INFO by default? For seeing the DEBUG levels, one needs to explicitly select it.

**Comment by shahsank3t** [comment]
@HeartSaVioR - could you please add a `ascending` queryParam to `/topologies/{topologyId}/logs` API to address point 1.

@arunmahadevan - for point 2, you mean to select all levels (except DEBUG) by default when the user lands on log search page?

**Comment by HeartSaVioR** [comment]
#1206

**Comment by arunmahadevan** [comment]
@shahsank3t , for point 2 - if user does not select any specific level, shouldn't it display all the levels ? If they want specific levels they can explicitly select it. @HeartSaVioR , does the backend API return all the log levels if there are no "level" params?

**Comment by HeartSaVioR** [comment]
@arunmahadevan No, we have default log levels as "INFO", "WARN", "ERROR". #1076

**Comment by arunmahadevan** [comment]
Merged #1210 to master
