### ISSUE TITLE
SAM UI - Dashboard view should open in a new tab

### ISSUE THREAD

**Issue by hmcl** [hortonworks/streamline#1216]
Upon clicking to open Dashboard, it should open in a new tab similarly to what happens for Registry and Topology (Ambari) Views. Currently it opens in the same tab and forces the user out of SAM

![image](https://user-images.githubusercontent.com/10284328/36277875-00b5bb32-1247-11e8-930d-b108588ef237.png)

**Comment by shahsank3t** [comment]
PR: https://github.com/hortonworks/streamline/pull/1227 fixes this

**Comment by arunmahadevan** [comment]
thanks @joylyn @shahsank3t , merged the changes to master.
