### ISSUE TITLE
Exclude system streams from component time-series metric

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1222]
The name of stream which contains `--` as prefix denotes system stream, like streams from/to acker.

We're aggregating all the values for all streams via `seriesAggregationFunction` parameter in AMS query, which includes the values from system streams, ends up having doubled value as aggregated value.

It would be much accurate if we just get all the streams and aggregate values manually with excluding system streams.

**Comment by arunmahadevan** [comment]
@HeartSaVioR thanks for the fix.

Merged https://github.com/hortonworks/streamline/pull/1223 to master.
