### ISSUE TITLE
Enable test environment which don't require importing cluster

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#1231]
Along with #1230, we can reduce the steps for testing the topology.

At a minimum, we need to do several steps so that we can run test mode topology:

1. create cluster via importing cluster or setting up manual cluster
2. create environment and associate services

whereas running test topology don't require anything but making sure that Storm (and SR if necessary) is installed and properly configured to streamline node.

Test environment must be set to read-only.

**Comment by HeartSaVioR** [comment]
#1232

**Comment by arunmahadevan** [comment]
Thanks @HeartSaVioR , merged #1232 to master
