### ISSUE TITLE
Not able to delete app assigned to test environment

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1263]
Create an app and associate it with "Test Environment"

Deleting the app throws the below error:

Streaming engine is not reachable. An exception with message [Exception while requesting http://localhost:8080/topology/summary] was thrown.

**Comment by HeartSaVioR** [comment]
This should be taken care from backend.

**Comment by arunmahadevan** [comment]
thanks @HeartSaVioR , merged #1264  to master
