### ISSUE TITLE
Add icon for Atlas service

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1267]
SAM has option to import Atlas service, but the icon is missing. See screenshot.

<img width="755" alt="screen shot 2018-05-02 at 11 23 45 am" src="https://user-images.githubusercontent.com/6792890/39541725-74b3216a-4dfb-11e8-84ec-4586858e4c30.png">

**Comment by arunmahadevan** [comment]
@shahsank3t , can you take a look?

**Comment by shahsank3t** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/1270

**Comment by arunmahadevan** [comment]
Thanks @shahsank3t for taking care of this quickly. Merged the changes to master.
