### ISSUE TITLE
Output fields of a custom processor should honor the schema definition

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#1273]
Right now even if a field is set to optional ("optional": true) in the output schema, the generated output schema of the stream is "optional": false. This should not be the case.

Need to check for other components as well where UI generates the output schema based on the input schema. It should honor the "optional" property.

**Comment by sameer79** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/1297

**Comment by sameer79** [comment]
@arunmahadevan please confirm the issue has been resolved. 
AFAIK the PR #1297 has been merged, so we can close the relevant issue.
