### ISSUE TITLE
SAM aggregate processor doesn't show the aggregation function

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#1288]
Created a SAM app with an aggregate processor and after saving, when I then open up the aggregate processor, it doesn't show the aggregation function part of the processor.

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/1289

**Comment by arunmahadevan** [comment]
Backend validations added in https://github.com/hortonworks/streamline/pull/1290

**Comment by arunmahadevan** [comment]
Thanks @sameer79 , merged #1289 to master
