### ISSUE TITLE
Unable to save projection when using select all Projection Fields

### ISSUE THREAD

**Issue by paulvid** [hortonworks/streamline#1310]
The issue: UI (OK button) unresponsive when configuring a simple projection and using select all Projection Fields. When selecting fields one by one, using chrome, OK button is responsive.

Using Firefox, the OK button is never responsive.

![image001_thumb](https://user-images.githubusercontent.com/784035/44599619-ec8def00-a7a4-11e8-9d21-52f304f507d1.png)

**Comment by arunmahadevan** [comment]
@shahsank3t , can you take a look ? This appears to be the code in latest master.

**Comment by shahsank3t** [comment]
@arunmahadevan sure I'll take a look into it soon

**Comment by arunmahadevan** [comment]
@sameer79 thanks for addressing the issue, merged PR to master.
