### ISSUE TITLE
Not able to add rule in Rule processor if we use alphanumeric column name

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#1313]
When trying to add a rule to the “RULE” processor, an exception is thrown:
`An exception with the message "Either streams or SQL string should be specified". was thrown while processing request.`

Schema that causes this issue:

`{
 "type": "record",
 "name": "test",
 "fields": [
  {
   "name": "col1",
   "type": "string"
  },
  {
   "name": "col2",
   "type": "string"
  }
 ]
}
`

**Comment by shahsank3t** [comment]
PR https://github.com/hortonworks/streamline/pull/1315 fixes this issue

**Comment by arunmahadevan** [comment]
Thanks @shahsank3t merged to master.
