### ISSUE TITLE
Question about streaming engines

### ISSUE THREAD

**Issue by geoHeil** [hortonworks/streamline#534]
Hi thanks for this great project and the presentation yesterday. 

Which streaming engines besides storm are supported? Are there any plans to integrate with flink?

**Comment by harshach** [comment]
@geoHeil Thanks for you interest in the project. Currently we only have storm support and we are working on security and other main features at this point. Flink is in roadmap but not immediate.

**Comment by harshach** [comment]
@geoHeil Please open a github issue for adding Flink support. Also for any future discussions, we are maintaining a google group here https://groups.google.com/forum/#!forum/streamline-users.
If you are interested in adding the Flink support we are happy to help you on streamline side.
