### ISSUE TITLE
Build failure due to unresolved "registry-common" dependency 

### ISSUE THREAD

**Issue by manuzhang** [hortonworks/streamline#547]
Failed to build project common where dependency com.hortonworks.registries:registry-common:jar:0.1.0-SNAPSHOT cannot be found.

```
[ERROR] Failed to execute goal on project common: Could not resolve dependencies for project com.hortonworks.streamline:common:jar:0.1.0-SNAPSHOT: Failure to find com.hortonworks.registries:registry-common:jar:0.1.0-SNAPSHOT in https://repository.apache.org/content/repositories/snapshots/
```

I checked both http://nexus-private.hortonworks.com/nexus/content/groups/public/com/hortonworks/registries/registry-common/ and http://repo1.maven.org/maven2/com/hortonworks/registries/ but neither of them has the dependency.

**Comment by HeartSaVioR** [comment]
Hi @manuzhang , thanks for having interest on Streamline.

Currently you need to clone `Schema registry` project, and build & install via `mvn install` to build `Streamline` project. Schema registry project is used for defining schema on data source, so you may want to be also familiar with that project.

https://github.com/hortonworks/registry

**Comment by manuzhang** [comment]
okay, that works. It would be better if this can be documented in README.

**Comment by HeartSaVioR** [comment]
Yeah ideally we need to use non-SNAPSHOT version of `registry` project so that end-users or contributors don't need to build and install `registry` manually.

@harshach Do we have a plan to release `registry` explicitly and refer specific version of `registry` from Streamline?

**Comment by harshach** [comment]
@manuzhang @HeartSaVioR we are publishing registry artifacts https://mvnrepository.com/artifact/com.hortonworks.registries . 
@HeartSaVioR we should start referring to the maven artifact.

**Comment by sureshms** [comment]
This issue has been addressed. For now closing the issue.
