### ISSUE TITLE
Running in a dev environment?

### ISSUE THREAD

**Issue by amweiss** [hortonworks/streamline#569]
Running with the `streamline-dev.yaml` file, I can get the site to be up and running but I get "Not authorized" errors and when I try to connect to a remote system running HDP 2.6, it just adds a new "Not authorized" error. Is there a public way to actually run in a dev environment via the current java self-hosting or docker?

![image](https://cloud.githubusercontent.com/assets/30146/26012151/958d2530-3721-11e7-801d-c30ecb1192be.png)

**Comment by arunmahadevan** [comment]
@amweiss, authorizer requires you to run the application in kerberos mode. Authorizer and authentication modules are currently being developed and you can encounter issues. For now you may want try running without the authorizer. i.e. comment the following lines in the streamline-dev.yaml 
https://github.com/hortonworks/streamline/blob/master/conf/streamline-dev.yaml#L28-L31
