### ISSUE TITLE
'readerSchemaVersion' in Kafka config key is marked as optional but effectively required due to Flux

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#583]
Kafka Source has 'readerSchemaVersion' as `optional` config key and its default value is set to `null`.
But since Flux can't handle `null` value and throws an error, the key is effectively `required`.

Needs to change `readerSchemaVersion` to be `required`, or add a new constructor for AvroKafkaSpoutTranslator which excludes `readerSchemaVersion` from parameters so that it can be handled as `null`.

Moreover, we need to handle `empty string` as `null` for `readerSchemaVersion` as well since it throws NumberFormatException.

**Comment by satishd** [comment]
#585 resolves this issue.
