### ISSUE TITLE
Need to add metadata for Role_Admin

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#591]
While starting a server in secure mode, we create an admin role user but don't add metadata in it which breaks the UI.
We add it after running bootstrap.sh but if by any chance the end user forgets to run the script, we show a page conveying the same which doesn't come up right now due to missing metadata.

cc: @arunmahadevan @harshach

**Comment by harshach** [comment]
@arunmahadevan can you take a look at this.

**Comment by arunmahadevan** [comment]
@shahsank3t , pushed a patch to master. https://github.com/hortonworks/streamline/pull/592. Please check

**Comment by shahsank3t** [comment]
@arunmahadevan Thanks for the quick fix. Looks good.
