### ISSUE TITLE
StormMetadataResource endpoint returns 401 Unauthorized in secured cluster setup

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#595]
StormMetadataResource does not use Subject.doAs when hitting storm ui rest api to get information about topologies. Hence a 401 Unauthorized response is received. @hmcl  Any clue about this?

**Comment by hmcl** [comment]
It works on my test cases. I will see what I can do.

**Comment by hmcl** [comment]
https://github.com/hortonworks/streamline/pull/596
