### ISSUE TITLE
Kaka sink topic schema must exist

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#600]
Right now we are letting user deploy an application that has a kafka sink without validating if topic has an associated schema in SR or not. We need to add a validation that prevents user from deploying if the schema does not exist.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/dfbbd17a8ab4e43cd45cb3c1bbea203d70f2a8c5
