### ISSUE TITLE
UDF Table text needs to be cleaned up

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#621]
A lot of capitalized words that is mixed with Non capitalized. We should clean this up.
<img width="1058" alt="udf table" src="https://cloud.githubusercontent.com/assets/1417689/26380447/8a665964-3fd3-11e7-860d-8367cc1b19fe.png">

**Comment by harshach** [comment]
we should keep the name and display name, class name from the source. Group built-in and use uploaded ones differently and should order by user uploaded udfs first so that they can notice the ones that they uploaded first.

**Comment by shahsank3t** [comment]
Fixed in commit: 0e58a957c0b651a1cf6f4a75c165d3bc76b8b6f4
