### ISSUE TITLE
Service pool ambari URL text should be editable

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#622]
Currently ambari URL suggested text in the text box is not editable. It cannot also be copied to change it in a separate editor. Let's make that text editable.

The URL shown in the text box should have "ambari_host:port" and "CLUSTER_NAME" styled differently to help user understand what needs to be changed. Bold or slight color change, either works.

Also when I missed "clusters" in the URL, I just get a generic error, "Not a valid URL". Instead, we can throw an error that says, "Not a valid Ambari URL. Please follow the convention - http://ambari_host:port/api/v1/clusters/CLUSTER_NAME

**Comment by shahsank3t** [comment]
@sureshms @harshach the text inside the text box is just a placeholder and not text value. Do we want to show the complete text and let the user change in it?

**Comment by sureshms** [comment]
We should look at this when we are done with P0 items. But my answer is yes. Currently you have a example text. I need to look at it to type the ambari URL manually. This will be a much better experience.

**Comment by harshach** [comment]
@shahsank3t another annoying part with this is, if I enter wrong password or made a slight mistake in my url we reset the URL text box. I don't think we should do that this will allow user to re-enter password and correct small mistake in the URL. So if there is an error occurs lets keep the user entered URL as it is.

**Comment by sureshms** [comment]
@shahsank3t and @harshach, in build 362, I see this issue is fixed. I am closing this issue.
