### ISSUE TITLE
Add Manual Service Pool does not work

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#623]
After adding a manual service pool, 
1. Click + and select Kafka, no option appears and hitting OK does nothing. 
2. Click + and select Storm. Only Nimbus entry is shown, missing many other information necessary.

Need to check other services as well.

**Comment by shahsank3t** [comment]
@sureshms
Not sure which build you are using & if the services component were properly registered while running bootstrap.sh. I & @harshach verified on another cluster with the latest pull and it's working as expected.

**Comment by sureshms** [comment]
I think we should all use a single build to test. At this point in time, as @harshach pointed out, using different builds is causing this issue.
