### ISSUE TITLE
Service pool sorting by name should be case insensitive

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#625]
Create a service pool name aaa and Zzz. When you sort it by name, Zzz appears first. Sort by name should be case insensitive.

**Comment by shahsank3t** [comment]
@sureshms @harshach
We have a generic search API `"api/v1/catalog/search?detail=true&namespace=<cluster/namespace/topology>&sort=<fieldName>&desc=<true/false>"` to sort.

Example API path for service pool (sort by name):
`api/v1/catalog/search?detail=true&namespace=cluster&sort=name&desc=false`

Need to handle this case insensitivity issue on the backend.

**Comment by arunmahadevan** [comment]
@shahsank3t, can you try with https://github.com/hortonworks/streamline/pull/635 ?

**Comment by shahsank3t** [comment]
@arunmahadevan I tried your PR and it resolves all search (case insensitive) issues.
