### ISSUE TITLE
Sorting Environments does not work

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#626]
Both sort by Name and Last Updated results in the LOADING... text and results do not appear.

Some suggestions:
1. Can we not have Loading with dots appearing one at a time after that. Let's use the same consistent behavior for loading (spinning wheel).
2. Ensure that the sort by name is sorting in a case insensitive manner (that is aaa appears before Zzz).

**Comment by shahsank3t** [comment]
@sureshms 
Will provide a fix for the actual bug.
Regarding your suggestion#1, we use the spinning wheel as loading for inner components & Loading with dots for the whole page. It's a consistent behavior right now and if you faced something different in any case, let me know, I'll fix it.
Suggestion#2 has been fixed and merged by Arun
