### ISSUE TITLE
Kakfa source showing bootstrap servers field as [object Object] if protocol is PLAINTEXT

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#628]
![image](https://cloud.githubusercontent.com/assets/38649/26382104/a146e044-3fde-11e7-949e-cc593668900a.png)

**Comment by satishd** [comment]
Raised similar issue #606, this is true for kafka sinks also.

**Comment by shahsank3t** [comment]
@harshach
the screenshot that you have attached is not using latest master. We have already fixed this "[object Object]" issue.

**Comment by shahsank3t** [comment]
Just debugged this with @harshach this is legit and happening in latest master, will fix it.

**Comment by shahsank3t** [comment]
@harshach  this has been fixed, can you please verify and close it. Thanks.
