### ISSUE TITLE
Hdfs dependency validation while creating an environment

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#636]
While creating an environment that has either a Hive or HBase service from a service pool we need to add validation satisfying following conditions.

1. Only one instance of HBase or Hive service is selected
2. If Hbase and Hive are both selected they have to come from same service pool
3. Adding either Hbase or Hive to a service pool should automatically bring Hdfs from the same service pool

@sank
Let me know if you have any more questions regarding this

**Comment by shahsank3t** [comment]
Fixed and merged in commit: https://github.com/hortonworks/streamline/commit/6c06d010e75afe9699e864fad10bd7d0405e98a6
