### ISSUE TITLE
Streamline UI - Limit Stack of Exceptions Banners Shown

### ISSUE THREAD

**Issue by hmcl** [hortonworks/streamline#640]
When multiple exceptions of the same kind occur, we should limit the number of times a banner gets created. It takes significant effort to close all of them one by one in the UI. An option is to show the a counter with the number of times an exception of that particular type happened, or at least provide a way to close all the banners on one click.

![image](https://cloud.githubusercontent.com/assets/10284328/26409167/a3598028-4054-11e7-9261-839d57909337.png)

**Comment by harshach** [comment]
+1. 
@shahsank3t  lets limit the errors to last 2 known errors and also they should go away if ther user navigates to different page.

**Comment by shahsank3t** [comment]
Fixed & pushed in. https://github.com/hortonworks/streamline/commit/c8590ac38b749c92ae3e62adf7df4bc679b75a1d
