### ISSUE TITLE
Remove HBase config field from topology config

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#646]
We're relying on including resource files to the topology jar so putting HBase config in topology config is not in effect, and even it makes confusion. Better to remove it.

**Comment by priyank5485** [comment]
@HeartSaVioR There is a check here at https://github.com/hortonworks/storm/blob/HDF-3.0.0.0/external/storm-hbase/src/main/java/org/apache/storm/hbase/bolt/AbstractHBaseBolt.java#L60

Right now there is an understanding between UI and flux generation code that UI will put a map with hbase.rootdir as a key and value in topology level config under hbaseConf key. We configure hbase bolt using withConfigKey("hbaseConf").  Before we remove it from UI we need to make sure that either UI is setting an empty {} in json for hbaseConf or change AbstractHBaseBolt to not throw that exception on a null for configKey

**Comment by HeartSaVioR** [comment]
@priyank5485 
Oh OK. Thanks for the detailed explanation. 

Btw, since we're putting the resource files to the topology jar, I wonder we need to let user override the configuration. If we don't think we need to, we could just remove the config from the UI, and include the key to topology config with empty map.

After GA we need to get rid of putting the resources files, and provide flatten configuration map to the component directly to make sure spouts and bolts can connect to the multiple clusters. We can remove the placeholder config then.

**Comment by priyank5485** [comment]
I think for now we should go with not providing a way for user to override the configuration. Anyway in current state the only override we provided was hbase.rootdir. To provide other overrides we would need UI changes like a special dialog just to override hbase config. 

@shahsank3t  For GA then, we just need UI change to remove hbase.rootdir and putting an empty map with hbaseConf in topology config. Can you take it up and send me a patch? I will test the topology.

**Comment by shahsank3t** [comment]
@priyank5485 emailed you the UI patch.

**Comment by priyank5485** [comment]
https://github.com/hortonworks/streamline/pull/664

**Comment by HeartSaVioR** [comment]
Priyank's patch got merged. Closing this.
