### ISSUE TITLE
Toolbar editor mode improvements

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#647]
* We can't arrange components in folder. It would be better to support it.
* It would be better to support enter key to confirm folder name.
* We can apply multiple order changes at once but when I make change for folder, editor toolbar mode just exits. It might be better to keep mode until the user clicks the button with `check mark`.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/b458b5a36f961d6f21ad1b321ea14b81ffb1dfaa
