### ISSUE TITLE
In secure mode cluster config should only be required if there are hbase,hive,hdfs sinks

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#650]
![image](https://cloud.githubusercontent.com/assets/38649/26437924/cc87dbf4-40d4-11e7-80ba-8260cbbf5bf5.png)

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/df6629bfeac7a3b82ab6947bfd83062c647c1810
