### ISSUE TITLE
UI Modal configs should switch tabs where the required fields are

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#651]
![image](https://cloud.githubusercontent.com/assets/38649/26437953/f6a0bc4e-40d4-11e7-9507-cabe0eb80152.png)

In this case we've some required fields in security tab but user is not aware keep trying to click "Ok" and Modal box doesn't get dismissed and continue to deploy.
We've same behavior in all the modal boxes right in node configs.
We should switch to the tab where the input fields are required along and also its probably good to highlight Green line below the tab into red

**Comment by shahsank3t** [comment]
Fixed and merged in commit: https://github.com/hortonworks/streamline/commit/6c06d010e75afe9699e864fad10bd7d0405e98a6
