### ISSUE TITLE
Custom processor page related bugs

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#663]
Found these issues in build number 362:
~~1. No need to have red boxes around mandatory fields. Already * next to the field name indicates it~~
2. Add a config and choose the type to be a Number. Set the default to value to “abc”. It can still be added and ends up becoming NaN. We need validation as people type into these fields.
3. Change column name “Is Optional” to just "Optional"
4. ~~Don’t understand what the column “Is User Input” for?~~ Let's hide "Is User Input" in the UI. Let's make all the fields added by the user as "Is User Input" = yes. Drop the column "IsUserInput" from the table.
5. Proper spacing is needed for Tooltip column. Try entering a long text and see a lot of space on the right hand side of the text
6. Please get rid of the text in red - "Please add Config Fields"
7. Config field should not be mandatory. Please remove that check.

**Comment by shahsank3t** [comment]
@sureshms 
Point#4 - "Is User Input" is to ask whether that field's value will be added by user or will be read-only field.

**Comment by sureshms** [comment]
@shahsank3t, I did not notice "Is User Input" check box. So if "Is User Input" is checked, it means you must have default value to make it read-only field. Correct?

I don't know why we we need it. Do we know of any use case? We should just everything into User Editable and get rid of that check box and column. @priyank5485, what do you think?

**Comment by sureshms** [comment]
@shahsank3t and @priyank5485, I found the problem. In Json I had en space (Unicode 8194) as space and that is why I got an error. I am uploading the document you can use for testing.

The main bug is, the json error is not caught and displayed. The error is silently ignored and hitting the save just does nothing. Here is the stack trace of the error that is not caught and displayed:

> vendor.bundle.js:5 Uncaught SyntaxError: Unexpected token   in JSON at position 2
    at JSON.parse (<anonymous>)
    at http://sms3-1.openstacklocal:7777/js/application.js:40:31665
    at Array.map (native)
    at t.e (http://sms3-1.openstacklocal:7777/js/application.js:40:31620)
    at t.e (http://sms3-1.openstacklocal:7777/js/application.js:40:19564)
    at Object.r (http://sms3-1.openstacklocal:7777/js/vendor.bundle.js:5:18133)
    at a (http://sms3-1.openstacklocal:7777/js/vendor.bundle.js:5:14166)
    at Object.u [as executeDispatchesInOrder] (http://sms3-1.openstacklocal:7777/js/vendor.bundle.js:5:14381)
    at d (http://sms3-1.openstacklocal:7777/js/vendor.bundle.js:4:25760)
    at v (http://sms3-1.openstacklocal:7777/js/vendor.bundle.js:4:25886i

>

Attached is the JSON file causing the problem:
[t.txt](https://github.com/hortonworks/streamline/files/1032952/t.txt)

**Comment by sureshms** [comment]
Note that on Json error, whether the text is cut and pasted into input and output schema or uploaded, the error is silently ignored.

**Comment by sureshms** [comment]
I also update the issue text to capture the current set of issues.

**Comment by priyank5485** [comment]
@sureshms Regarding isUserInput field, here is the explanation. When a CP is registered it goes in to backend as a new Component Bundle. Each component has config fields. All other components will only have fields that user needs to enter value for. Think of them as instance variables. For CP, we also need static variables. customProcessorImpl, inputSchema, etc go in as static fields or with isUserInput=false so when a CP is dropped on an application user cant change them but still can see them. The fields entered as config fields on CP registration page are the instance variable fields.

Having said that, we can remove the check box isUserInput while adding config fields during registration of a CP and default it to true

**Comment by sureshms** [comment]
Spoke to @priyank5485. Here is the change required.
Let's hide "Is User Input" in the UI. Let's make all the fields added by the user as "Is User Input" = yes. Drop the column "IsUserInput" from the table.

**Comment by shahsank3t** [comment]
Fixed and merged in commit: https://github.com/hortonworks/streamline/commit/6c06d010e75afe9699e864fad10bd7d0405e98a6
