### ISSUE TITLE
Streamline view mode hover over text needs to be changed

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#670]
Currently the hovering over on any of the Source, Processors, and Sinks shows a comment box with grey background. This needs a UX review. Suggestion:
- Lets tone down this without high contrast grey background and model it similar to tool tip

**Comment by shahsank3t** [comment]
Fixed as per Houshang's mock in commit: https://github.com/hortonworks/streamline/commit/d06391802bf5c3ccbb8185cc975422b18db18015
