### ISSUE TITLE
Getting Started text improvement

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#671]
Currently the spacing does not look right for Getting Started text in My Applications, Service Pool, and Environment pages. Can we update it to look like the following (provided by Houshang)?
![screen shot 2017-05-26 at 10 05 02 am_thumb](https://cloud.githubusercontent.com/assets/1417689/26504884/56059674-41fb-11e7-99a9-b6dea321b873.png)

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9d7fb0b9e79eaee014c3e3f3ef4bc9aa150b8044
