### ISSUE TITLE
Remove flashing ellipsis and use spinning wheel to show progress indicator

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#674]
Can we replace the flashing ellipsis as progress indicator with spinning wheel? The current experience is not very good. It looks like a stuttering, flashing dots.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/eb9cebdb3eb671b1ebb19f3972cbec6b8bc95b3a
