### ISSUE TITLE
UI: Authorizer issues

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#677]
1. UserIcon on top right has a dropdown with un-clickable links
<img width="162" alt="screen shot 2017-05-26 at 2 06 03 pm" src="https://cloud.githubusercontent.com/assets/5951352/26512703/9c035596-421c-11e7-8cfc-594f11135c94.png">

2. On adding new user, clicking on any user does not show the edit pane. (workaround, switch to roles tab, then switch back to user tab for edits)

3. On edit user page, adding application access does not stick. Logging as that user does not show the application.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/df6629bfeac7a3b82ab6947bfd83062c647c1810

**Comment by ggolani** [comment]
verified with build 400 that the above issues are fixed.
