### ISSUE TITLE
Authorizer: Sharing

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#678]
Issue 1:  Admin cant share application owned by user A(role: dev) to user B(role:dev)

Issue 2: After application is shared with user B, user B cannot edit, clone, export, delete application

**Comment by harshach** [comment]
cc @arunmahadevan

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/df6629bfeac7a3b82ab6947bfd83062c647c1810

**Comment by ggolani** [comment]
Issue 2 is fixed, Issue 1 is still open, Tracking it with, https://github.com/hortonworks/streamline/issues/696
