### ISSUE TITLE
Authorizer: anonymous user error message

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#679]
As of now, if a user who is not in Streamline db logs on, they get the following error message,
<img width="341" alt="screen shot 2017-05-26 at 3 07 40 pm" src="https://cloud.githubusercontent.com/assets/5951352/26514183/219ee802-4225-11e7-9285-060da95d551b.png">

Improve the error message by posting a friendly message with email address of the super-user/admin for getting access.

**Comment by harshach** [comment]
I'll ask Houshang to provide error screens

**Comment by harshach** [comment]
UI changes are done, waiting on my change on server side
