### ISSUE TITLE
Authorizer: combo roles issues

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#681]
- Developer + Operations role: If the user is a developer role first and then operations role was added, The menu icons next to the applications show edit grayed out but clicking them allows for editing if the developer role didnt own or share the application
<img width="570" alt="screen shot 2017-05-26 at 4 23 54 pm" src="https://cloud.githubusercontent.com/assets/5951352/26515531/84f8d2b8-4230-11e7-9058-503f40bd77f6.png">
<img width="1196" alt="screen shot 2017-05-26 at 4 23 13 pm" src="https://cloud.githubusercontent.com/assets/5951352/26515532/84fc1f2c-4230-11e7-817b-603988242dd0.png">

- Developer + Admin role: If the user is a developer role first and then admin role was added, user administration is not enabled.
<img width="1239" alt="screen shot 2017-05-26 at 4 25 38 pm" src="https://cloud.githubusercontent.com/assets/5951352/26515534/89839d36-4230-11e7-8a52-700b6220c2b9.png">

- Analyst + Operations role: if a user is an analyst role first and then operations role was added, the service pool and environments menu is not enabled.

**Comment by shahsank3t** [comment]
@harshach This is related to UI, assigning it to myself.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/df6629bfeac7a3b82ab6947bfd83062c647c1810

**Comment by ggolani** [comment]
verified with build 400 that these are resolved
