### ISSUE TITLE
Reduce the cursor size when editing the application name

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#684]
Cursor size seems to be very large. See the screenshot
<img width="197" alt="cursor-size" src="https://cloud.githubusercontent.com/assets/1417689/26523942/39455e96-42d9-11e7-97d6-2ceb7ce927a9.png">
 below:

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9d7fb0b9e79eaee014c3e3f3ef4bc9aa150b8044
