### ISSUE TITLE
In application view mode, we should show the version of the application running

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#686]
Currently in the view mode, we show the latest edited version of the Application/topology instead of what is running. But the operational aspects of topology is related to the version that is running.

Here are my thoughts:
1. If the application is running, show the running version.
2. If it is not running, then show the latest version.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9d7fb0b9e79eaee014c3e3f3ef4bc9aa150b8044
