### ISSUE TITLE
Imported topology Rules processor not showing fields in the Rule

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#692]
![image](https://cloud.githubusercontent.com/assets/38649/26561798/fea6b994-4475-11e7-8df0-4e341b92fdb6.png)
In the above , we expect to see votes['funny'] in selected field name

**Comment by harshach** [comment]
@shahsank3t also we should use "==" to signify the "equals"

**Comment by shahsank3t** [comment]
@harshach 
"==" is throwing error from backend while saving the rule.

> {"responseMessage":"An exception with message [org.apache.calcite.sql.parser.SqlParseException: Encountered \"= =\" at line 1, column 48.\nWas expecting one of:\n    <EOF> \n    \"ORDER\" ...\n    \"LIMIT\" ...\n    \"OFFSET\" ...\n    \"FETCH\" ...\n    \"GROUP\" ...\n    \"HAVING\" ...\n    \"WINDOW\" ...\n    \"UNION\" ...\n    \"INTERSECT\" ...\n    \"EXCEPT\" ...\n    \"MINUS\" ...\n    \"NOT\" ...\n    \"IN\" ...\n    \"BETWEEN\" ...\n    \"LIKE\" ...\n    \"SIMILAR\" ...\n    \"=\" \"+\" ...\n    \"=\" \"-\" ...\n    \"=\" \"NOT\" ...\n    \"=\" \"EXISTS\" ...\n    \"=\" <UNSIGNED_INTEGER_LITERAL> ...\n    \"=\" <DECIMAL_NUMERIC_LITERAL> ...\n    \"=\" <APPROX_NUMERIC_LITERAL> ...\n    \"=\" <BINARY_STRING_LITERAL> ...\n    \"=\" <PREFIXED_STRING_LITERAL> ...\n    \"=\" <QUOTED_STRING> ...\n    \"=\" <UNICODE_STRING_LITERAL> ...\n    \"=\" \"TRUE\" ...\n    \"=\" \"FALSE\" ...\n    \"=\" \"UNKNOWN\" ...\n    \"=\" \"NULL\" ...\n    \"=\" <LBRACE_D> ...\n    \"=\" <LBRACE_T> ...\n    \"=\" <LBRACE_TS> ...\n    \"=\" \"DATE\" ...\n    \"=\" \"TIME\" ...\n    \"=\" \"TIMESTAMP\" ...\n    \"=\" \"INTERVAL\" ...\n    \"=\" \"?\" ...\n    \"=\" \"CAST\" ...\n    \"=\" \"EXTRACT\" ...\n    \"=\" \"POSITION\" ...\n    \"=\" \"CONVERT\" ...\n    \"=\" \"TRANSLATE\" ...\n    \"=\" \"OVERLAY\" ...\n    \"=\" \"FLOOR\" ...\n    \"=\" \"CEIL\" ...\n    \"=\" \"CEILING\" ...\n    \"=\" \"SUBSTRING\" ...\n    \"=\" \"TRIM\" ...\n    \"=\" <LBRACE_FN> ...\n    \"=\" \"MULTISET\" ...\n    \"=\" \"ARRAY\" ...\n    \"=\" \"SPECIFIC\" ...\n    \"=\" <IDENTIFIER> ...\n    \"=\" <QUOTED_IDENTIFIER> ...\n    \"=\" <BACK_QUOTED_IDENTIFIER> ...\n    \"=\" <BRACKET_QUOTED_IDENTIFIER> ...\n    \"=\" <UNICODE_QUOTED_IDENTIFIER> ...\n    \"=\" \"ABS\" ...\n    \"=\" \"AVG\" ...\n    \"=\" \"CARDINALITY\" ...\n    \"=\" \"CHAR_LENGTH\" ...\n    \"=\" \"CHARACTER_LENGTH\" ...\n    \"=\" \"COALESCE\" ...\n    \"=\" \"COLLECT\" ...\n    \"=\" \"COVAR_POP\" ...\n    \"=\" \"COVAR_SAMP\" ...\n    \"=\" \"CUME_DIST\" ...\n    \"=\" \"COUNT\" ...\n    \"=\" \"CURRENT_DATE\" ...\n    \"=\" \"CURRENT_TIME\" ...\n    \"=\" \"CURRENT_TIMESTAMP\" ...\n    \"=\" \"DENSE_RANK\" ...\n    \"=\" \"ELEMENT\" ...\n    \"=\" \"EXP\" ...\n    \"=\" \"FIRST_VALUE\" ...\n    \"=\" \"FUSION\" ...\n    \"=\" \"GROUPING\" ...\n    \"=\" \"LAST_VALUE\" ...\n    \"=\" \"LN\" ...\n    \"=\" \"LOCALTIME\" ...\n    \"=\" \"LOCALTIMESTAMP\" ...\n    \"=\" \"LOWER\" ...\n    \"=\" \"MAX\" ...\n    \"=\" \"MIN\" ...\n    \"=\" \"MOD\" ...\n    \"=\" \"NULLIF\" ...\n    \"=\" \"OCTET_LENGTH\" ...\n    \"=\" \"PERCENT_RANK\" ...\n    \"=\" \"POWER\" ...\n    \"=\" \"RANK\" ...\n    \"=\" \"REGR_SXX\" ...\n    \"=\" \"REGR_SYY\" ...\n    \"=\" \"ROW_NUMBER\" ...\n    \"=\" \"SQRT\" ...\n    \"=\" \"STDDEV_POP\" ...\n    \"=\" \"STDDEV_SAMP\" ...\n    \"=\" \"SUM\" ...\n    \"=\" \"UPPER\" ...\n    \"=\" \"VAR_POP\" ...\n    \"=\" \"VAR_SAMP\" ...\n    \"=\" \"CURRENT_CATALOG\" ...\n    \"=\" \"CURRENT_DEFAULT_TRANSFORM_GROUP\" ...\n    \"=\" \"CURRENT_PATH\" ...\n    \"=\" \"CURRENT_ROLE\" ...\n    \"=\" \"CURRENT_SCHEMA\" ...\n    \"=\" \"CURRENT_USER\" ...\n    \"=\" \"SESSION_USER\" ...\n    \"=\" \"SYSTEM_USER\" ...\n    \"=\" \"USER\" ...\n    \"=\" \"NEW\" ...\n    \"=\" \"CASE\" ...\n    \"=\" \"NEXT\" ...\n    \"=\" \"CURRENT\" ...\n    \"=\" \"CURSOR\" ...\n    \"=\" \"ROW\" ...\n    \"=\" \"(\" ...\n    \"[\" ...\n    \"IS\" ...\n    \".\" ...\n    \"(\" ...\n    ] was thrown while processing request."}

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/62bd7c50d25cf85a3a706b3a0061d0a8809f4485
