### ISSUE TITLE
Editing Authorizer -> Roles -> Operations throws and error

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#697]
Change the display name for Operations roles and hit save. Error "An exception with message [null] was thrown while processing request." is thrown.

Interestingly, this error happens, only if you saved another role prior to the above operation.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9843c01c2e9a9023ce344dbf56cbe22679afeaba
