### ISSUE TITLE
Roles UI improvement

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#699]
Against each Role we have small squares that indicates access control. Unless someone hovers over that, no one understands what those boxes mean. Given access control is listed on the right hand side, my preference is to get rid of these boxes.

<img width="529" alt="roles" src="https://cloud.githubusercontent.com/assets/1417689/26603101/7e6fccd2-453a-11e7-9342-01dac36010f5.png">

@harshach, for your visibility.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/d06391802bf5c3ccbb8185cc975422b18db18015
