### ISSUE TITLE
Remove user name display on the top right hand corner

### ISSUE THREAD

**Issue by sureshms** [hortonworks/streamline#700]
Let's make the hexagon to the left of it clickable showing the same information shown when the current name is clicked. Also, let's remove the user name. It is shown when the icon is clicked.
<img width="299" alt="user name" src="https://cloud.githubusercontent.com/assets/1417689/26603264/13333020-453b-11e7-9845-21f8ae53f084.png">

One other issue I noted is, if you edit email address, role for the the user logged in, clicking the user name currently does not show updated information. Looks like we are caching it and it may be good to refresh the data from the backend.

**Comment by harshach** [comment]
@shahsank3t lets remove hexagon icon that we are using instead fall-back to older user icon.
Also we should add Logout option to clear out the cookie and remove any links in the text that are not pointing to any page.

**Comment by shahsank3t** [comment]
@harshach 
so just to clear out, we'll remove the hexagon icon as well as username and have that old user icon.
On clicking that icon, we will show all info that we are currently showing as well as logout option. Right?

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9843c01c2e9a9023ce344dbf56cbe22679afeaba
