### ISSUE TITLE
Add version file and return it as part of command line and API

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#702]

**Comment by harshach** [comment]
https://github.com/hortonworks/streamline/pull/703

**Comment by harshach** [comment]
@shahsank3t we should add this to the UI at the top before the user role icon

**Comment by harshach** [comment]
actually lets add it to the bottom of the navigation bar when it expands

**Comment by shahsank3t** [comment]
@harshach cool, I'll add it to the bottom of the navigation bar.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9843c01c2e9a9023ce344dbf56cbe22679afeaba
