### ISSUE TITLE
UDF table should use displayName from backend to display "Name"

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#705]
The name field in the api is for internal use (e.g NumberSum vs Sum). UI should use the displayName field and display it as Name in the table.

**Comment by arunmahadevan** [comment]
<img width="1208" alt="screen shot 2017-05-31 at 1 08 32 pm" src="https://cloud.githubusercontent.com/assets/6792890/26620976/a771c4e6-4602-11e7-90ed-133d0edcecda.png">

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/9843c01c2e9a9023ce344dbf56cbe22679afeaba
