### ISSUE TITLE
Keys should be optional in aggregate processor

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#707]
Right now one always needs to select one or more keys in the aggregate processor.

This should be optional so that aggregate per window can be computed.

E.g. count of events in the last 5 mins
mean age of users for events in the last 1 hr and so on

**Comment by sureshms** [comment]
@arunmahadevan, when key is not specified, you aggregate over all the events in the window without any group by?

**Comment by harshach** [comment]
Moving this out of 0.5.0 release.

**Comment by arunmahadevan** [comment]
@sureshms , if the key is not present the aggregate is performed over all the events in the window (window is the implicit group-by key). E.g. count of events in the window, sum/mean/topn of some field of events in the window etc.

**Comment by shahsank3t** [comment]
Fixed in commit: b701447d79d0015f00a05cb072d2bfe324b250bf
