### ISSUE TITLE
Not able to add default value in schema once the schema is saved.

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#708]
1. Create a schema with some fields E.g.
```
{
 "type": "record",
 "name": "test",
 "namespace": "com.hortonworks.registries",
 "fields": [
  {
   "name": "business_id",
   "type": "string"
  }
 ]
}
```

2. Save

3. Click edit and now change the definition of field as 

```
  {
   "name": "business_id",
   "type": "string",
    "default": "x"
  }
```

4. Enter some description
5. Save

UI throws a message saying "Schema version already present" and does not save the changes.

**Comment by shahsank3t** [comment]
@arunmahadevan Is this meant for registry project?

**Comment by arunmahadevan** [comment]
Right - raised https://github.com/hortonworks/registry/issues/136
