### ISSUE TITLE
debug logs location for streamline and schema-registry

### ISSUE THREAD

**Issue by ggolani** [hortonworks/streamline#711]
right now logs for streamline and schema-registry point to: /usr/hdf/current/{streamline, registry}. Can we standardize it to be accessible from /var/log.

**Comment by harshach** [comment]
@ggolani in ambari installed streamline, registry /usr/hdf/current/streamline/logs is symlinked /var/log/streamline and /var/log/registry. Let me know if thats not the case

**Comment by ggolani** [comment]
confirmed with build 408, it is not the case.
an instance to try out (172.22.123.251), use hdf-qe-keypair.pem

**Comment by harshach** [comment]
@ggolani its the QE code the redirects the symlink of all the applications to /grid/0/log
![image](https://cloud.githubusercontent.com/assets/38649/26668932/c3432922-4660-11e7-9b9f-b4ac29f3015e.png)

In general if a user installed it via Ambari , it will put this symlink to /var/log/streamlne
