### ISSUE TITLE
Topology message timeout value suggestion

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#713]
Currently, topology message timeout (seconds) setting at application level defaults to 30 seconds. It is error prone to always use that value because if user has an Aggregate or Join processor with a time based window of greater than message timeout, it will cause timeout failures at runtime in the topology.  We need a UI change so that when user clicks on Deploy and we show topology level settings dialog, we come up with a value suggested using the logic below.

1. If there is no Aggregate or Join processor in topology then use the default 30 seconds.
2. If there is one or more Aggregate or Join, the default value should be sum(Window Length + Sliding Interval) + delta (2 seconds) for each Aggregate or Join processor that has a time based window. Note that window interval could be in minutes. So we will need to convert it to seconds and set the default value accordingly. 

This is based on discussion with @harshach and @arunmahadevan

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/d06391802bf5c3ccbb8185cc975422b18db18015
