### ISSUE TITLE
Projection processor dialog is not dismissed on clicking OK

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#714]
1. Create a Kafka source with yelp_review topic
2. Connect it to a projection processor and enter the projection fields
3. Click Ok - Nothing is happening.

<img width="1219" alt="screen shot 2017-06-01 at 6 12 13 pm" src="https://cloud.githubusercontent.com/assets/6792890/26680238/33a99486-46f6-11e7-8d8e-ad735d5562b1.png">

**Comment by satishd** [comment]
This is a known issue, UI expects at least one UDF to be added even though it is not mandatory to use UDFs. 
@arunmahadevan As a workaround, you can use IDENTITY function for one of those fields.

**Comment by arunmahadevan** [comment]
@satishd , ok I was not aware of this. 

If its something that can be easily fixed we should do it now to avoid confusion.

If not at-least make the field mandatory or throw some message in the UI.

**Comment by shahsank3t** [comment]
@arunmahadevan - I am under the impression that UDF is a mandatory field, if it's not, I'll remove those validations.

**Comment by satishd** [comment]
@shahsank3t Having UDF is not mandatory, you can remove that restriction if possible.
