### ISSUE TITLE
The Notification sink UI is hard-coded

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#717]
Right now the notification UI is hardcoded for email notifier. So even if one uploads a custom notifier, theres no way to configure this via the Notification sink UI, hence for now we can

1. Hide the upload ("+") icon in notifiers
2. Remove the fields displaying the email notifier and class name
3. Remove console notifier from bootstrap.

**Comment by arunmahadevan** [comment]
<img width="586" alt="screen shot 2017-06-01 at 6 50 22 pm" src="https://cloud.githubusercontent.com/assets/6792890/26681763/dc1e7226-46fb-11e7-9bf2-3ce544b05d17.png">

**Comment by shahsank3t** [comment]
@arunmahadevan 
Notification sink is not hard coded. Was there something you tried to change in configuration but didn't get changed?

**Comment by arunmahadevan** [comment]
@shahsank3t , Right now the fields are coming from topology component bundle for 'Notification' and the fields are hard-coded for email notifier. Can UI support multiple entries in topology component bundles with type SINK and subType NOTIFICATION? If it is, still the user needs to run bootstrap with some UI specification which will be painful. I will try this out.

Better, we can show the users the list of registered notifiers in a dropdown and have a way to derive the required UI fields via the notifier Implementation class itself (e.g via some annotation). This can be done post GA.

**Comment by shahsank3t** [comment]
alright, I'll just do the changes you mentioned above and post GA we can support rest of the things.

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/a5c7cd51c347ff554df49f6a4ea84f68651b12eb

**Comment by priyank5485** [comment]
@arunmahadevan To answer your question
Can UI support multiple entries in topology component bundles with type SINK and subType NOTIFICATION?

We already do that for CP.
