### ISSUE TITLE
Change CP output stream name to have a suffix that is user friendly

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#718]
We changed CP output stream name to have custom_processor_<nodeid> where node id is the processor id in the catalog of processors. This is not very user friendly when we connect two instances of same CP in to a join processor. Talked to @shahsank3t and seems to be non trivial change. I think this is not a blocker we should try to get this change in.

**Comment by shahsank3t** [comment]
@priyank5485 Few things we didn't think about while deciding on using `componentName+'_stream_'+id`:

When user drops the another instance of the same component, UI adds the unique identifier `componentName-<count>` (example: CCP, CCP-1, CCP-2, etc)
So using this name if we create stream it will be something like: `CCP_stream_1`, `CCP-1_stream_2`, `CCP-2_stream_3`.

This is pretty user-friendly, but I believe backend throws runtime exception while deploying a topology if streamId has a hyphen (-) in it. 

Can you confirm if it's true or not?

**Comment by sureshms** [comment]
@priyank5485, can you please talk to Harsha and get this prioritized?

**Comment by shahsank3t** [comment]
Had a discussion with @priyank5485 and just to summarize the issue:
Currently, if you have 2 custom processors that have output streams named as “custom_stream_1”, “custom_stream_2” and both are being connected to Join processor.
Being an end user, he might not be aware that “custom_stream_1” is coming for which custom processor so we wanted to change the streamId (output stream name) to something that user can figure out visibly from the UI as well as it should be unique but currently we don’t have any such unique value.

As a turn around for this issue, the user can click on the link between 2 components and check stream name (as visible in the image below) that is being passed to next component and use that info while configuring processors.

<img width="480" alt="screen shot 2017-06-03 at 2 53 13 pm" src="https://cloud.githubusercontent.com/assets/6761317/26752393/6e14ffe4-486c-11e7-8136-039e31b6aa93.png">

So IMO, this shouldn’t be a blocker(P0) for the release and should be moved out from this release.

cc: @sureshms @harshach

**Comment by harshach** [comment]
Thanks @shahsank3t . This works as designed. We will see if there are further improvements based on user feedback.
