### ISSUE TITLE
Projection processor not populating fields with values in streamline event

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#720]
Application created at 
http://angel-hdf2.field.hortonworks.com:7777/#/applications/3/edit?_k=pxl6pr
Storm topology at 
http://angel-hdf1.field.hortonworks.com:8744/topology.html?id=streamline-3-Trucking-IOT-App-2-10-1496429305
Ambari hosts
http://angel-hdf0.field.hortonworks.com:8080/#/main/hosts

The processor named Split which is of type Projection is connected to 3 CPs at the same time. For some reason the StreamlineEvent sent to each of the CPs does not seem to have any key value pairs populated. As a result, all 3 CPs are throwing exceptions and throwing NPEs. I checked yaml generated and json passed in to the RulesBolt constructor and it looks good. But something going wrong at runtime in RulesBolt that is not processing the tuple as expected

**Comment by satishd** [comment]
@shahsank3t It seems UI is not setting right type for UDFs for returned values. Can you set them appropriately in the schema?

**Comment by satishd** [comment]
<img width="1155" alt="screen shot 2017-06-03 at 6 12 33 am" src="https://cloud.githubusercontent.com/assets/2577761/26749175/b40eb498-4823-11e7-86f5-2ed03df92552.png">

@shahsank3t You can see right-down that `splitJoinValue` and `week` do not have types, they should have been `long` and `int` respectively as it was shown in UDF page like below.

<img width="1001" alt="screen shot 2017-06-03 at 6 15 14 am" src="https://cloud.githubusercontent.com/assets/2577761/26749220/281a0b76-4824-11e7-921c-d29ff67dbf67.png">
<img width="1000" alt="screen shot 2017-06-03 at 6 15 23 am" src="https://cloud.githubusercontent.com/assets/2577761/26749221/294db6fa-4824-11e7-99a7-c8b597af6134.png">

**Comment by shahsank3t** [comment]
UI is just not showing the type of the field (I'll fix this) but is setting the type properly in passing the JSON data (outputStream) to the backend.

Check here (Projection Processor API): http://angel-hdf2.field.hortonworks.com:7777/api/v1/catalog/topologies/3/versions/9/processors/49

**Comment by satishd** [comment]
Now, it seems to have right types being set on those streams but UI is showing them as empty. 
This may be an intermittent issue as it seems george mentioned in mail that he was getting those types as default to double ignoring UDF's return types.

@priyank5485 Can we redeploy the topology and check whether it is encountering the same issue or not?

**Comment by priyank5485** [comment]
Yes. I will redeploy

**Comment by priyank5485** [comment]
Redeployed and still seeing the same issue. Checked the yaml file and splitJoinValue field is passed as long.

**Comment by priyank5485** [comment]
@satishd Dont worry about this issue. I figured out the issue. inputSchemaMap needed for CP is not being passed by UI for some reason so CP is at fault. Sorry about pulling you on this.

@shahsank3t Attaching screenshot here. This was working last night. I tested it on my cluster. This is the topology i tested and checked data in kafka sink. http://u14-priyank-streamline-2.openstacklocal:7777/#/applications/361/edit?_k=952ikr 

Did something accidentally change? I know you were giving me individual patches for UI fixes but then you combined them all in one to send it to Harsha. Can you please check?
![screen shot 2017-06-02 at 7 41 49 pm](https://cloud.githubusercontent.com/assets/5192436/26749936/e1bcd012-47cb-11e7-8b8b-46980c9976f9.png)

**Comment by priyank5485** [comment]
Attaching a screenshot from last night from my cluster that it was working last night.
![screen shot 2017-06-02 at 7 45 31 pm](https://cloud.githubusercontent.com/assets/5192436/26749951/22a566b6-47cc-11e7-839f-75520b155b16.png)

**Comment by shahsank3t** [comment]
@priyank5485 This was a genuine bug which worked before for you coz you manually might have mapped individual input fields. Auto-filling those fields and just hitting save was not saving that complete object.
Fix has been merge in, can you please take the latest pull and check. Thanks.
