### ISSUE TITLE
Custom processor config property outputSchema has key as undefined

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#722]
Not sure if its related to connecting 3 CPs  to a JOIN processor but i noticed that CP config property outputStreamToSchema has a key as undefined whereas it should actually be the output stream of that processor. Attaching an image and related urls.

http://angel-hdf0.field.hortonworks.com:8080/#/main/hosts
http://angel-hdf2.field.hortonworks.com:7777/#/applications/4/edit?_k=3tq8ao
![screen shot 2017-06-02 at 5 35 48 pm](https://cloud.githubusercontent.com/assets/5192436/26749238/abfd975a-47bb-11e7-8295-03256ba42a4e.png)

**Comment by shahsank3t** [comment]
Fixed it in commit: https://github.com/hortonworks/streamline/commit/fd2abb4c38c982a2901ffcc215cef0550af1c6f7
