### ISSUE TITLE
If topology name is big, listing page gets misaligned

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#732]
![image](https://cloud.githubusercontent.com/assets/38649/26793760/0be02c36-49d4-11e7-8d56-0f36d600cf5a.png)

After going to topology editor and back to listings page
![image](https://cloud.githubusercontent.com/assets/38649/26793777/17dfd202-49d4-11e7-8b42-20d494d00ca4.png)

**Comment by shahsank3t** [comment]
Fixed in commit: 0e58a957c0b651a1cf6f4a75c165d3bc76b8b6f4
