### ISSUE TITLE
CSS fixes for Microsoft Edge browser

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#739]
Attached below are the screenshots of the pages where CSS is not proper in Edge browser.

<img width="1140" alt="screen shot 2017-06-06 at 8 17 53 pm" src="https://cloud.githubusercontent.com/assets/6761317/26835331/b87c17bc-4af5-11e7-8eb9-64e5bde86ce8.png">
<img width="1140" alt="screen shot 2017-06-06 at 8 18 14 pm" src="https://cloud.githubusercontent.com/assets/6761317/26835329/b8703e06-4af5-11e7-8789-99db813174c2.png">

Jar name missing while updating existing custom processor
<img width="1135" alt="screen shot 2017-06-06 at 8 18 28 pm" src="https://cloud.githubusercontent.com/assets/6761317/26835333/b8ce1d32-4af5-11e7-9bf1-2028da31437e.png">

<img width="1139" alt="screen shot 2017-06-06 at 8 18 41 pm" src="https://cloud.githubusercontent.com/assets/6761317/26835332/b87fc772-4af5-11e7-9e40-b4185b4ca789.png">
<img width="1139" alt="screen shot 2017-06-06 at 8 18 54 pm" src="https://cloud.githubusercontent.com/assets/6761317/26835330/b8737d6e-4af5-11e7-9b65-25774674703a.png">

**Comment by husain79** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/788
