### ISSUE TITLE
Streamline initial screen in secure mode

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#740]
1. Install streamline in secure mode (build 448)
2. Hit streamline URL E.g. http://arun-hdf-secure-448-1.openstacklocal:7777/
3. It gives a page with hints (see screenshot)

Issues:
1. For firefox, the message mentions "sam-ui-hostname:7799" but I am hitting streamline at port 7777, it can be confusing for users. So the message can be made generic "sam-ui-hostname:PORT" or can include the actual port.

2. For chrome, it mentions only registry-ui-hostname. Streamline hostname missing here ?

Maybe we can just display the message relevant to the browser the user is using, and show the instructions for other browsers as some expandable option.

<img width="901" alt="screen shot 2017-06-06 at 2 08 27 pm" src="https://user-images.githubusercontent.com/6792890/26852408-0e6b058a-4ac3-11e7-89a8-63485f683c40.png">

**Comment by harshach** [comment]
@shahsank3t what we should do here is to replace this with the current browsers url hostname. So that users can copy paste that directly.

**Comment by sameer79** [comment]
Raised PR #799
