### ISSUE TITLE
Add logout link to invalidate the kerberos auth cookie

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#745]

**Comment by shahsank3t** [comment]
@harshach Since the cookie is a `httpOnly` cookie (a cookie with the httpOnly parameter set), we cannot clear it from JavaScript. 
As a turnaround, what I suggest is making an API that will clear the cookie and UI can make that call on clicking "Logout" link.

**Comment by harshach** [comment]
@arunmahadevan  can you take this up.

**Comment by joylyn** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/798 to add UI side of changes.
