### ISSUE TITLE
Topology Export/Import or Clone if a service is not present component dialog box shows empty.

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#747]
1. Build a topology with Environment that has Kafka in it.
2. Export this topology.
3. Create a new Environment without Kafka in it.
4. Import the topology into the new environment.
5. Click on Kafka source , the options are shown a blank. We should show the fields and throw an error saying the Kafka cluster is not available .

cc @shahsank3t

**Comment by shahsank3t** [comment]
Fixed in commit: https://github.com/hortonworks/streamline/commit/eb9cebdb3eb671b1ebb19f3972cbec6b8bc95b3a
