### ISSUE TITLE
Support transaction between multiple DB operations

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#763]
Streamline runs multiple DB operations in a service REST API call, which could be failing in the middle of operations. That's not atomic and really hard to restore to the previous state when it fails.

So it would be really great to support transaction and apply it to whole Streamline operations.

**Comment by arunmahadevan** [comment]
To start with we can add support for beginTransaction, commit, rollback to Storage manager and start using it in the resource/service class methods. We could also consider frameworks like JOOQ or Spring but I think that would be a bigger refactoring.

**Comment by raju-saravanan** [comment]
I have proposed a solution for this issue, [here](https://github.com/hortonworks/registry/issues/273)

**Comment by HeartSaVioR** [comment]
#987 resolved this.

NOTE: #987 enables transaction for all resource methods by default. The plan from @raju-saravanan is changing the default behavior to 'no transaction'. After that we could apply more fine-grained transaction.
