### ISSUE TITLE
Implement FileSync to synchornize the jars uploaded from one server onto another

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#765]
Currently, we expect users to use HDFS as the FileStorage incase of HA, so that the users uploading jar from one server connection can be seen on another server. This is a heavy dependency on HA and we should look into implementing a FileSync and default LocalFileStorage and remove HDFS as required FS incase of HA.
cc @arunmahadevan and @satishd please add if you have any thoughts on this.
This will be needed for registry as well.

**Comment by harshach** [comment]
Initial Idea of implementation
1. When user uploads the resources/jar, we will add the hostname in the db table (origin server)
2. FileSyncManager
  2.1 FileSyncThread monitors the necessary tables/resources checks if the file listed in db exists in the folder, if not makes a request to the origin server via rest apis to download the jar (incase of secure cluster we will use the streamline server principal and given its admin this shouldn't cause any authorizer exception)  
  2.2 During the startup the FileSyncManager checks and downloads if necessary
  2.3 Based configurable period of time for syncs

**Comment by arunmahadevan** [comment]
I think at a high level this can be provided as a workaround for HA, but there may be corner cases like the origin server going down after the file was uploaded but before it could be synced by the follower and so on.

**Comment by satishd** [comment]
We should have minimum replicas before it returns from the upload call as successful. This is a standard pattern on how many replicas it should have, if user needs HA and do not care about storing in all the nodes across the cluster then can say replicate on all nodes. This can be configured by user or set as ALL by default.

**Comment by arunmahadevan** [comment]
The standard pattern also needs a co-ordination service like ZK, I am not sure if we want to add ZK as a dependency instead of having to set up HDFS.

May be we can just store the file as a blob into the DB itself and avoid the replication problems altogether.

**Comment by satishd** [comment]
We can avoid having ZK and explore using https://github.com/hortonworks/ratis in SAM nodes for coordination. I guess we should avoid pushing jar binaries into DB.

**Comment by HeartSaVioR** [comment]
For streamline, backend RDBMS is just a `source of truth`. It's a SPOF regardless of Streamline H/A. So easiest way to do it would be putting blob into DB. Yes sure I don't like it, but might be OK with having local metadata cache. (Do read and write blobs if it is really needed.)

If we want to avoid having blob data on RDBMS, I don't think there's easy way to do this without adding external component. My experience with Nimbus H/A and BlobStore is actually not good. It adds huge complexity to the Nimbus even it relies on ZK but still have many corner cases. 

So if we can rely on HDFS, I think that is the best. If not, I'd like to see the simplest way to do it, even though that doesn't guarantee true H/A, or having redundancy.

**Comment by harshach** [comment]
@HeartSaVioR @arunmahadevan @satishd 
1. Adding external component like zk is no go. 
2. We already have simpler HA solution which is to have mysql/postgres whichever db to be HA. In most production installations this is true.
3. current approach of HA works for us without having to add any additional operational dependency. The only exception to this is FileStorage.

Ratis is one option that we could explore but do we even need this and unlike Nimbus HA where most of the issues due to zk connection and loosing the leadership. In our case,

1.  All servers are active there is no leader/follower
2.  We can introduce a new config called streamline.hosts which will have list of all hosts of servers listed. We can introduce min.sync.replicas
3. User uploads a custom processor at this time the write succeed if it can upload it to atleast min.sync.replicas. The request can be sent any server and it will forward it to rest of servers based on min.sync.replicas
4. If there is a host that doesn't receive the resource during the upload time. We can follow the approach that I described with FileSyncManager.

The metadata of the resource is written to HA storage (mysql, phoneix) what we are doing is just a resource file copy. This is not the same as what happens nimbus HA or blobstore so same issues will not applicable here.

**Comment by HeartSaVioR** [comment]
Suppose we write the location for the file to the DB (source of truth):

1. If we write `first uploaded host` as the location of file:

The host is SPOF and sync will stop when the host crashes.

2. If we write the all locations of replicas as the location of file:

That might be OK for availability, but we don't detect the failures hence replicas are not updated for failure cases. So sync process should try all replicas with handling failure nodes. Blobstore H/A utilizes ZK's ephemeral node which acts as failure detector.

Btw, we assume background resource file sync, but maybe we also need foreground sync when a request needs some resources but it is not in sync for this node yet. All the nodes are active so all the nodes should be able to handle the request at any time.

**Comment by arunmahadevan** [comment]
@harshach , @HeartSaVioR 
I think as a workaround storing the jars as a blob into DB may be the easiest workaround (that lets us do away with HDFS dependency for HA). This will delegate the replication to the db (if users need HA they will anyway have a db cluster with master-master or a master-slave setup).  I feel building a custom replication solution without a co-ordinator can be error prone and require us to handle different corner cases.

**Comment by HeartSaVioR** [comment]
I'm +1 to store jars as a blob into DB as a workaround. It is both easiest (simplest) and safest. 
(We're using DB as reliable source, so that shouldn't have any issues for safeness)

Just to reiterate, I know it is the thing to avoid. But if it might be the best approach, do we need to avoid it? If we worry about slowness, we can maintain local file cache and implementing it is much easier.

I still think using HDFS is ideal. So if we could make this optional and let users select either HDFS or DB, that should be better.

**Comment by harshach** [comment]
@HeartSaVioR @arunmahadevan lets try going with db blob for now. We can re-visit this if that doesn't workout.
