### ISSUE TITLE
conflict between  registry start and streamline server  port/adresses

### ISSUE THREAD

**Issue by pgibert** [hortonworks/streamline#767]
Hello,
when starting in any order  registry  server  
 _bin/registry-server-start.sh conf/registry.yaml.inmemory.example_ 
and streamline server
_bin/streamline-server-start.sh  conf/streamline-dev.yaml_

i got a runtime exception 
java.net.BindException: Address already in use
if i run one and not the other , it  starts ....... and i can get the GUI for each 
phil

**Comment by harshach** [comment]
@pgibert I think the conflict could be in adminPort. Can you please change them to different ports 
https://github.com/hortonworks/streamline/blob/master/conf/streamline.yaml#L72

https://github.com/hortonworks/registry/blob/master/conf/registry.yaml.inmemory.example#L59
in the registry config after the above line, add 
`adminConnectors:
    - type: http
      port: 8082`

**Comment by pgibert** [comment]
hello , thanks both start  now :-)
but clicking Registry icon on the left streamline menubar  it referecnes  
_http://localhost:9090/#/schema-registry_ not the IP of the host where the registry is running
i mean should be  _http://<myIP>:9090/#/schema-registry_ .
A config set up also to be done ?
best regards 
phil

**Comment by arunmahadevan** [comment]
@pgibert, you can set the schema registry hostname in the streamline yaml like [here](https://github.com/hortonworks/streamline/blob/master/conf/streamline.yaml#L15)

**Comment by pgibert** [comment]
yes thanks sorry it was under my eyes just corrected it  and not it is ok  thanx again

**Comment by pgibert** [comment]
it ok now both started  the streamline dev server  + registry serverwith correct url.
but the status seems not good 
./streamline  status 
_Streamline is not running. No pid file found._

./streamline  setup
_Running Streamline Setup.
Password:_
and i do not know  what is the passwd asked here ? should i run the postgre or mysql config  in place of the dev config for streamline 
best regards

**Comment by pgibert** [comment]
./streamline  version
0.3.0-SNAPSHOT

**Comment by harshach** [comment]
@pgibert for any questions can you please use this group https://groups.google.com/forum/#!forum/streamline-users
