### ISSUE TITLE
Remove properties and fieldValues from email notifier

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#770]
While registering notifiers the properties and field values are not used currently. We can remove it for now.

**Comment by shahsank3t** [comment]
@arunmahadevan 
I am unaware if the backend is using / not using properties & field values but those are used in following scenarios on UI:

1. If a topology is created using an environment having manually added cluster with `email service`, we show it's values directly into Notification sink (`properties`) when the user wants to configure it.

2. We add `fieldValues` into Rule/BranchRule's `action` array (with key: `outputFieldsAndDefaults`)

First one, I can handle on UI itself and not add/show any value if we hide values but for the second, should we pass a blank object or something else?

cc: @harshach

**Comment by shahsank3t** [comment]
@harshach This issue has nothing to do with UI. It is just to get rid of values that were being added in bootstrap-notifier.sh and those values are not touched by UI in any manner. Assigning back to @arunmahadevan

**Comment by shahsank3t** [comment]
This issue has been fixed and merged in PR https://github.com/hortonworks/streamline/pull/771
