### ISSUE TITLE
Streaming Analytics Manager Application status issue 

### ISSUE THREAD

**Issue by zoharsan** [hortonworks/streamline#802]
When an application deployment fails due to some errors (in this case, atlas hook missing jars for example), the application shows in running state in SAM console. I can also see the storm topology running from the Storm UI.
When trying to kill that app from the Streaming Analytics Manager UI, it fails to kill it with the following message:
An exception with message [Invalid action for current state: TOPOLOGY_STATE_DEPLOYMENT_FAILED] was thrown while processing request.
The only way to get out of this state is to kill the Storm topology on the Storm UI.
There are two issues with this:
- What is the actual state of the app? For Storm, it is running. For SAM, it is not and its status is TOPOLOGY_STATE_DEPLOYMENT_FAILED. This needs to be clarified.
- The ability to kill the app from the SAM UI without having to go to the Storm UI.

**Comment by arunmahadevan** [comment]
@zoharsan , can you upload the stack trace and relevant parts of the streamline log if you have it?

**Comment by zoharsan** [comment]
Find attached the log. Look for string TOPOLOGY_STATE_DEPLOYMENT_FAILED

[streamline-2017-07-11-0.log.gz](https://github.com/hortonworks/streamline/files/1142540/streamline-2017-07-11-0.log.gz)
