### ISSUE TITLE
Upload Custom Processor hangs on bad schema

### ISSUE THREAD

**Issue by mattf-horton** [hortonworks/streamline#804]
In the HDF 3.0 release version of Streamline, the Upload Custom Processor UI hangs forever if you give it an input schema that has correctly formatted JSON but is inappropriate for the input schema field.

HOW TO REPRO:

1. Obtain a working uploadable Custom Processor, such as the example ENRICH-PHOENIX CP documented at https://docs.hortonworks.com/HDPDocuments/HDF3/HDF-3.0.0/bk_getting-started-with-stream-analytics/content/ch07s05s02.html 
1. In a working install of HDF3.0, open the SAM UI in a browser, and select Configuration : Application Resources : Custom Processor.  
1. Press "+" to add a new CP.
1. Fill in the form for a CP upload.  When you get to the "input schema" field, where the correct content would be:
```
[
  {
    "name": "eventTime",
    "type": "STRING",
    "optional": false
  },
...
]
```
(Note: replace the ellipses "..." with more content from the example, as documented.)

Instead put in correctly formatted JSON with incorrect content, such as:
```
{fields: [
  {
    "name": "eventTime",
    "type": "STRING",
    "optional": false
  },
...
]
}
```
Do similarly with the "output schema" field.

When the form is completely filled out, press "Save" to start the upload.

RESULT:

The upload hangs forever with the message "Uploading custom processor. This might take a few minutes...".  I waited half an hour and it never timed out or gave any useful feedback.  

The error shown in Chrome Developer Tools is:
```
vendor.bundle.js:5 Uncaught SyntaxError: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at t.e (application.js:41)
    at t.e (application.js:40)
    at Object.r (vendor.bundle.js:5)
    at a (vendor.bundle.js:5)
    at Object.u [as executeDispatchesInOrder] (vendor.bundle.js:5)
    at d (vendor.bundle.js:4)
    at v (vendor.bundle.js:4)
    at Array.forEach (<anonymous>)
    at n (vendor.bundle.js:6)
```
Screen shot attached.
![image](https://user-images.githubusercontent.com/908957/28091749-eff75fd8-6645-11e7-9ebf-48c1c8b19bbb.png)

**Comment by arunmahadevan** [comment]
The input and output schema should be without the "fields" key and a JSON array as below:
`
[
  {
    "name": "eventTime",
    "type": "STRING",
    "optional": false
  },
...
]
`

That said, the UI should throw proper error to alert the user. Theres a similar issue filed already - https://github.com/hortonworks/streamline/issues/801

The documentation should also be fixed with the right schema text.

**Comment by shahsank3t** [comment]
https://github.com/hortonworks/streamline/pull/814 PR has been raised to fix this issue

**Comment by shahsank3t** [comment]
PR has been merged.
