### ISSUE TITLE
Rules processor should provide Advanced tab to write sql for more complex rule

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#809]
We should provide a good editor to write up sql statement including syntax helper. Along with convention to refer to schema fields. We should same notation that we use everywhere else to refer to the fields.
cc @hmcl 
On the rules processor side we should be able to accept the sql statement an run that.

**Comment by shahsank3t** [comment]
https://github.com/hortonworks/streamline/commit/2f8f71d9eafd41c20cb55453bfec3450d6e6199b implements this feature.
