### ISSUE TITLE
Integration test cases are failing on master

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/streamline#818]
I am running into following issues while doing "mvn clean install",

ERROR [2017-07-14 13:47:05,018] com.hortonworks.streamline.streams.service.TopologyCatalogResource: Got exception: [RuntimeException] / message [Corresponding namespace not found: 1] / related resource location: [com.hortonworks.streamline.streams.service.TopologyCatalogResource.removeTopology](TopologyCatalogResource.java:262)
! java.lang.RuntimeException: Corresponding namespace not found: 1

ERROR [2017-07-14 13:47:05,066] com.hortonworks.streamline.streams.service.NamespaceCatalogResource: Got exception: [AlreadyExistsException] / message [Namespace entity already exists with name nstest] / related resource location: [com.hortonworks.streamline.streams.service.NamespaceCatalogResource.addNamespace](NamespaceCatalogResource.java:166)
! com.hortonworks.streamline.storage.exception.AlreadyExistsException: Namespace entity already

**Comment by HeartSaVioR** [comment]
#792 contains the fix, but looks like reviewing is not in progress right now. I'll craft a new patch only for fixing this.

**Comment by HeartSaVioR** [comment]
523688474f8d2b83d40444048110eab2d1dfb053 for master
1e2a9ff51f765719330bdbca1dde4443812bdeea for HDF-3.0-maint

Tested before committing via locally build.
Closing.
