### ISSUE TITLE
Abstract out object serialization logic from Resource file and keep them in their respective JsonSerializer

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/streamline#820]
* In StreamlineConfigurtionResource, we expose StreamlineConfiguration through "/api/v1/config/streamline" API. The serialization logic is written in the resource file could be abstracted out into its own JsonSerializer, which can be plugged into StreamlineConfiguration class with JsonSerialize annotation at the class level.
* Another minor refactoring could be, StreamlineConfiguration classes and Resource class can be kept into their respective packages under webservice.

**Comment by HeartSaVioR** [comment]
Resolved via #819
