### ISSUE TITLE
Support variable arguments for UDFs

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/streamline#831]
Currently, a UDF that can take variable number of arguments is not supported. An example is CONCAT. However, there are some issues with Calcite recognizing it as a built in function as mentioned by @arunmahadevan in another issue. This issue is created to track the requirement and feasibility of supporting built-in or custom UDFs that can have variable arguments.

**Comment by shahsank3t** [comment]
@priyank5485 
I think what you are suggesting here is duplicate of https://github.com/hortonworks/streamline/issues/706
Can you please verify and if it's that the case, mark duplicate and close this one.
Thanks.

**Comment by priyank5485** [comment]
Yes it is a duplicate. Closing this.
