### ISSUE TITLE
Streamline should take comma-separated registry servers

### ISSUE THREAD

**Issue by harshach** [hortonworks/streamline#835]
Registry supports HA and the client needs to have set of registry servers to choose in-case other is not available. We should support comma-separated registry servers as part of registry.url config and able to query in a round-robin fashion if the first server doesn't work.

**Comment by satishd** [comment]
Default `SchemaRegistryClient` already supports round-robin with failover strategy for url selection. [SchemaResource](https://github.com/hortonworks/streamline/blob/master/streams/service/src/main/java/com/hortonworks/streamline/streams/service/SchemaResource.java) and kafka serializer/deserializers use the default `SchemaRegistryClient`.

@harshach Pl let me know if I am missing anything here.

**Comment by satishd** [comment]
Closing this PR as clusterUrl is already handled by `SchemaRegistryClient`.
