### ISSUE TITLE
Schema versioning and programmatic upgrade with a framework like liquibase

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/streamline#849]
Currently, all the necessary schema migrations are kept in one file. Instead of this approach, we should consider breaking down each SQL statements into their respective files and use a framework like liquibase to do SQL migration. With this approach, any new changes that have to be introduced to the SQL entities could be versioned and could be applied on top of an existing database depending upon how far behind the existing database from the latest version.

**Comment by arunmahadevan** [comment]
Thanks @raju-saravanan , merged https://github.com/hortonworks/streamline/pull/861 to master
