### ISSUE TITLE
Provide a migration script for UDF/UDAFs

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#859]
The internal name for streamline provided UDF/UDAF are now appended with `_FN`. This is to migrate the data in the DB for any UDFs users may have used earlier with the older name.

**Comment by harshach** [comment]
@raju-saravanan may be we could use liquibase to automate this?
cc @arunmahadevan

**Comment by raju-saravanan** [comment]
@harshach sure, I will take this up

**Comment by arunmahadevan** [comment]
The changes are addressed with #861.
