### ISSUE TITLE
UI doesn't allow putting Ambari HTTPS URL for importing

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#878]
<img width="1083" alt="screen shot 2017-08-10 at 9 55 19 am" src="https://user-images.githubusercontent.com/1317309/29149931-4070674c-7db2-11e7-80b3-eda9655dec41.png">

As I looked into developer tool in safari, there's no request on backend side.

@harshach Do we also need to fix this as well as HDF-3.0-maint?

**Comment by shahsank3t** [comment]
@HeartSaVioR 
UI doesn't do validation on whether it's http or https in URL. The reason you are seeing the error is that of missing "clusters" string in your URL as visible in the screenshot. :) It should be **api/v1/clusters/cl1**

Could you please try adding clusters and verify again. Thanks.

**Comment by HeartSaVioR** [comment]
@shahsank3t Sorry that seemed to just my miss. Closing this. Thanks for reminding.
