### ISSUE TITLE
Test mode: Show output events as it becomes available

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#894]
Sometimes the storm process keeps on running and the test run never completes until one manually kills the storm local mode process. 

1. Add a "Stop" Button to invoke the kill API to forcefully stop the test run.
2. For better UX experience, poll the test running API and show the results on-the-fly.

That way even if the process gets stuck, the user can stop the test run after they have seen the expected results and even if the process does not get stuck it will be useful in general.

**Comment by sameer79** [comment]
PR: https://github.com/hortonworks/streamline/pull/908 fixes this issue
