### ISSUE TITLE
Test mode: Provide an option to force stop a test run

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#899]
Sometimes the storm process keeps on running and the test run never completes until one manually kills the storm local mode process.

That way even if the process gets stuck, the user can stop the test run after they have seen the expected results and even if the process does not get stuck it will be useful in general.

**Comment by HeartSaVioR** [comment]
One thing to note: 
When we force kill the process, the test would be marked as 'failed' in history entity, because killed process will return non-zero return code. If we would ignore the return code, we can't determine whether test topology was running or now. 
So at least for now it may not be a good idea to use this in general.

**Comment by sameer79** [comment]
Raised PR: https://github.com/hortonworks/streamline/pull/908 for the UI changes
