### ISSUE TITLE
Test Mode: Need a field to identify when to start polling of event logs

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#901]
Currently, when we hit 'testhistories' API, in background actual process take some time before starting the actual worker but there's no way to identify when that worker starts writing the logs into the file because of which UI calls 'events' API and get error: 'Event log file of history 17 does not exist or is not readable.'

UI needs a flag/field in 'testhistories' API that when set to true, UI can start polling on 'events' API and gets proper data/error.

**Comment by HeartSaVioR** [comment]
I have a slightly plan to address #892 which could help on addressing this, but that would need huge work.
So let's just make it simple. I'll just make '/events' available immediately when UI requests test run.
