### ISSUE TITLE
Test Mode: Deleting a topology source node after a test source node is configured throws exception

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#907]
Steps to reproduce:
1. Configure a topology with more than one source
2. Go to test mode and configure a test case
3. Go back to edit mode and try to delete any one of the configured sources

Exception was thrown:
"An exception with message [com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`streamline_db`.`topology_test_run_case_source`, CONSTRAINT `topology_test_run_case_source_ibfk_2` FOREIGN KEY (`sourceId`, `versionId`) REFERENCES `topology_source` (`id`, `versionId`))] was thrown while processing request."

**Comment by HeartSaVioR** [comment]
I missed that we are running topology test with current version of topology, so that any sources, processors, sinks can be removed. 
For workaround we should remove foreign key constraints, and maybe in future we need to revisit how topology test feature can play well with topology versioning.

**Comment by HeartSaVioR** [comment]
Or maybe we want to also remove associated test source or test sink when topology source or topology sink is removed, since we may want to keep existing test case valid even we remove one of topology source or sink associated to test source or test sink for that test case.

**Comment by HeartSaVioR** [comment]
PR available: #909
