### ISSUE TITLE
Test Mode: Getting an exception on deleting a test case that has been ran successfully once

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#910]
Steps to reproduce:
1. Configure the whole topology
2. Go to test mode => create & configure a test case (Suppose, TC1)
3. Run the test case and let it complete.
4. Create & configure another test case  (Suppose, TC2)
5. Now try to delete TC1, it throws error:

{"responseMessage":"An exception with message [com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`streamline_db`.`topology_test_run_histories`, CONSTRAINT `topology_test_run_histories_ibfk_2` FOREIGN KEY (`testCaseId`) REFERENCES `topology_test_run_case` (`id`))] was thrown while processing request."}

**Comment by HeartSaVioR** [comment]
This is due to FK so I would like to drop FK in streamline_db.topology_test_run_histories, but I'm stuck on creating a new sql file for flyway which drops existing foreign key in existing table.
We don't use constraint symbol, so we should fetch the name from meta of RDBMS, which I feel not trivial to make it only from SQL statements.

@arunmahadevan @raju-saravanan Any ideas?

**Comment by arunmahadevan** [comment]
@HeartSaVioR was the table topology_test_run_histories present in earlier release ? if not can we update the create_tables.sql itself and drop the constraint. We also need to review the sql and see if all the constraints are droppabe with alter constraints for future.

**Comment by arunmahadevan** [comment]
Raised https://github.com/hortonworks/streamline/issues/911 for reviewing create tables script

**Comment by HeartSaVioR** [comment]
@arunmahadevan Topology test feature was hidden in UI but available in backend. I think we included  the table in earlier released version(s). Moreover if we would want to drop constraint from another table the issue will be raised again.

**Comment by HeartSaVioR** [comment]
I'm not familiar with stored procedure both MySQL and PostgreSQL, but googled it a bit, looks like we might be able to drop all existing foreign keys in tables. 
If then we could add a sql file which drops all existing keys (not only foreign key but also index key regardless of uniqueness other than primary key) and alters tables to re-add all keys with naming them.

So maybe we need to find MySQL and/or PostgreSQL procedure experienced folks, and also need to check that Flyway can execute stored procedure without any issue.

**Comment by HeartSaVioR** [comment]
I just tried out MySQL stored procedure for dropping foreign keys (we could even drop all keys) in a table.

```
DROP PROCEDURE IF EXISTS dropForeignKeysFromTable;

delimiter ///
create procedure dropForeignKeysFromTable(IN param_table_name varchar(255))
begin
    declare done int default FALSE;
    declare dropCommand varchar(255);
    declare dropCur cursor for
        select concat('alter table ',table_schema,'.',table_name,' DROP FOREIGN KEY ',constraint_name, ';')
        from information_schema.table_constraints
        where constraint_type='FOREIGN KEY'
            and table_name = param_table_name
            and table_schema = database();

    declare continue handler for not found set done = true;

    open dropCur;

    read_loop: loop
        fetch dropCur into dropCommand;
        if done then
            leave read_loop;
        end if;

        set @sdropCommand = dropCommand;

        prepare dropClientUpdateKeyStmt from @sdropCommand;

        execute dropClientUpdateKeyStmt;

        deallocate prepare dropClientUpdateKeyStmt;
    end loop;

    close dropCur;
end///

delimiter ;
```
After registering stored procedure, `CALL dropForeignKeysFromTable('topology_test_run_histories');` can drop all foreign keys in `topology_test_run_histories`.

This also works with Flyway, so we could apply what I've described from previous comment: add a sql file which drops all existing foreign keys and alters tables to re-add all foreign keys with naming them.
We don't have keys only for indexing, and looks like all unique keys are having symbol, so looks like we only need to handle FK for keys for now.

**Comment by arunmahadevan** [comment]
@HeartSaVioR nice. Assuming we can come up with something similar for Postgres, we can go with this.

**Comment by HeartSaVioR** [comment]
@arunmahadevan OK. I guess I found similar stored procedure for PostgreSQL, but I haven't used PostgreSQL for a while so need to set up for my local. Will update with the result.
