### ISSUE TITLE
Test mode: Validate test case data on clicking OK

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#917]
When the test case data is saved, it needs to be validated to see if its compatible with the current source output schema.

The sources can be edited and schema changed later, and that looks OK because validation will be also happening at runtime.

**Comment by shahsank3t** [comment]
Assigning this to myself as well since the need to work on the UI side of things.

**Comment by sameer79** [comment]
Rasied PR https://github.com/hortonworks/streamline/pull/926
