### ISSUE TITLE
Improve the commit process and remove the CHANGELOG

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#923]
Right now its getting difficult to track what issues got fixed in different branches. Sometimes we don't put ISSUE in the commit message, sometimes its BUG- and sometimes there are multiple commits for fixing an issue.

We need to follow some conventions for the commits like 
1. Mandatorily have ISSUE- in the commit  message 
2. strictly one commit per issue
3. Preferably have some script that can squash and validate the restrictions and merge.

This will make it easy to track the issues that got fixed in different branches and compare the branches.

**Comment by arunmahadevan** [comment]
Also consider integrating with build (travis) since we often see build failures after patches are merged to master.

**Comment by satishd** [comment]
Good to have tests target to be run in internal gerrit repo commit tasks also. We may need to discuss on whether github repo should be maintained as root and gerrit as mirror of that to allow non horotnworks committers to commit directly into root repo.

**Comment by HeartSaVioR** [comment]
Basically I would like to craft merge script which pulls the branch, and squashes commits into one, and merge without merge commit. (We can borrow Spark merge script and modify a bit to achieve it easily.)

There may be some considerations about merge script:

> 2. strictly one commit per issue

As I talked with @arunmahadevan we could allow exceptional cases: a PR has multiple authors. In this case we should respect authorship, so shouldn't squash commits or should squash commit per author (without breaking commit sequence). Not sure we would want to consider this at now and make it automatically.
