### ISSUE TITLE
SAM Processors/Sinks/Rules need to update when its upstream components are updated

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#933]
When an upstream component of a RP/Projection/Branch etc is updated, the rule does not seem to get updated with the updated input stream.

**Comment by shahsank3t** [comment]
Adding myself as the assignees too, since it needs to be handled on UI as well.

**Comment by sameer79** [comment]
Raised PR https://github.com/hortonworks/streamline/pull/945

**Comment by arunmahadevan** [comment]
Addressed via 
https://github.com/hortonworks/streamline/pull/934
https://github.com/hortonworks/streamline/pull/945
