### ISSUE TITLE
The edge fields grouping does not update on selecting different keys in aggregate

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#941]
1. Create a Kafka -> Aggregate topology, selecting some field as the key
2. Edit the Aggregate and select a different field as the key and save
3. The edge fields grouping still refers to the old field as the key. 

It should be updated to the new key (or keys). 

Please check similar behavior in other processors like join.

**Comment by shahsank3t** [comment]
Fixed this bug and added supported for Real-Time Join processor in https://github.com/hortonworks/streamline/pull/948#pullrequestreview-66067904
