### ISSUE TITLE
Update React & React-Dom version

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#946]
Facebook has [released](https://facebook.github.io/react/blog/2017/09/26/react-v16.0.html) a new version (16 & 15.6.2) with MIT license. We need to update these libraries and make changes if anything is breaking with this update.

**Comment by M-ZubairAhmed** [comment]
Can I help you with this? Shall I update and fix what's breaking?

**Comment by sameer79** [comment]
@M-ZubairAhmed  I have almost done, just verifying my test cases.

**Comment by M-ZubairAhmed** [comment]
ok sure

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/947
