### ISSUE TITLE
Join bolt does not work in Test mode

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/streamline#951]
Created a simple topology,

 (Kafka1, Kafka2) --- Join --- Kafka

No output is produced in the test mode.

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
Is this still valid? We had tested test mode event correlation with that topology and Join processor works.

**Comment by HeartSaVioR** [comment]
Did #889 resolve this?

**Comment by arunmahadevan** [comment]
This is no longer an issue
