### ISSUE TITLE
While configuring a custom source, getting schema using version API has undefined string in it.

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#954]
Seems like "topic" field is hardcoded and so it works fine for Kafka but when @priyank5485 tried to add custom source, he ran into this issue.

**Comment by shahsank3t** [comment]
https://github.com/hortonworks/streamline/pull/955 fixes this

**Comment by arunmahadevan** [comment]
Merged https://github.com/hortonworks/streamline/pull/955 to master
