### ISSUE TITLE
Handle cleanups of componentBundleId into topologyEditorToolbar on deletion of any source/sink bundle

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/streamline#956]
UI seems to be handling only delete of processor bundles and so on deleting source/sink bundles, UI is not clearing "bundleId" into topologyEditorToolbar API because of which user cannot configure the node.

**Comment by shahsank3t** [comment]
https://github.com/hortonworks/streamline/pull/957 fixes this

**Comment by arunmahadevan** [comment]
Merged https://github.com/hortonworks/streamline/pull/957 to master
