### ISSUE TITLE
Test mode: Add event correlation

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#964]
We need to add some correlation so that events can be tracked down from the source and how it got transformed at different stages.

E.g Lets say we emit an event E1 from a kafka source via a topology like 
 
        Kafka -> Aggregate -> Notification
                   -> Projection -> Kafka
                   -> Rule -> Hbase
 
User should be able to track the event and see how it got transformed at different stages. E.g showing a tree structure that can be expanded could be one option.
 
         E1
           - K1 (output from kafka)
               - A1 (Output of aggregate)
               - P1  (Output of projection)

I think we may need apis like,
What are the different groups of related events in a test run
Which are the parent event(s) for a given event.

Based on this UI could display some kind of a tree structure that can be expanded from the source event.

**Comment by HeartSaVioR** [comment]
Me, @arunmahadevan, @shahsank3t discussed about this topic the day before yesterday.

Backend needs to provide below via REST API to UI:
- list of correlation event IDs which each of them represents root event ID
- tree of events for specific correlation event ID for getting full event tree
- subtree of events for specific correlation event ID and also specific event ID

Each event should contain information which we are already providing via event log API. 
Given that we don't want to plot to edge, we may remove "target component name" and "target stream id" from current.

**Comment by sameer79** [comment]
Raised PR : https://github.com/hortonworks/streamline/pull/979
