### ISSUE TITLE
Schema (size) is limited by meta store data type

### ISSUE THREAD

**Issue by rtempleton** [hortonworks/streamline#984]
After altering the SR table to accommodate larger schemas: https://github.com/hortonworks/registry/issues/287

We then encountered problems in streamline due to data type limitations. Needed to apply the following alter table to account for the change in Streamline:
ALTER TABLE topology_stream MODIFY fieldsData MEDIUMTEXT;

**Comment by arunmahadevan** [comment]
@rtempleton , 

ALTER TABLE topology_stream MODIFY fieldsData MEDIUMTEXT;

 is this the only change you had to make in the SAM schema?

**Comment by priyank5485** [comment]
https://github.com/hortonworks/streamline/pull/1064

**Comment by arunmahadevan** [comment]
Thanks @priyank5485 for the patch, merged #1064 to master and HDF 3.1.0.0
