### ISSUE TITLE
Aggregate processor assigns id/name in Storm topology which is different from Streamline component id/name

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/streamline#985]
<img width="1095" alt="screen shot 2017-10-26 at 2 01 24 pm" src="https://user-images.githubusercontent.com/1317309/32035760-318af7b6-ba56-11e7-847c-9db26ba6acf8.png">

Above topology is converted to Storm topology as below:

<img width="916" alt="screen shot 2017-10-26 at 2 00 47 pm" src="https://user-images.githubusercontent.com/1317309/32035773-479c6468-ba56-11e7-8ca1-f87e27784db6.png">

As we can see from above screenshot, bolt for `DriverAvgSpeed` has a name as `streamlineID.sequence-WindowedRulesProcessor` which doesn't match to origin streamline component. All the things which relies on ID or name would be broken: for example, metrics.

**Comment by HeartSaVioR** [comment]
The name part also affects on test mode, so I applied the normalization of ID and name from #972 .
(Also fixed to use origin component name for windowed rule bolts rather than  'WindowedRulesProcessor'.)

It assumes that a streamline component can have multiple windowed rules which each of rule should be matched to a bolt. That means, we should aggregate the metrics, events, errors, logs from multiple bolts (ID.seq) to a streamline component (ID).

For test mode events, we are referencing component as component name so it would be fixed after normalizing ID and name. (This mean #977 will also resolve a part of this issue for test mode.)

For metrics, metrics will be published to bolts' component name: ID.seqnum-componentName even with the best effort. Hence we should do some aggregations when querying metrics from backend side. Backend should be able to enumerate component name(s) for Storm, but need to think about how. Handling errors is same.

For log search what we're exploring, it depends on whether search engine supports kind of wildcard pattern. If search engine supports wildcard, we could query with component name as `streamlineID*-component name` to avoid enumerating component name(s) for Storm. If search engine doesn't support wildcard, we end up enumerating component name(s), as same as metrics.

**Comment by HeartSaVioR** [comment]
We could take another approach as well: separating Aggregate Processor from Rules Processor. 

The thing why it is going to be such complicated is the concept that a streamline component can match to multiple bolts. We don't allow multiple windowing in Aggregate Processor so in fact there shouldn't be no issue on above, but we integrated Aggregate Processor to Rules Processor and made it as one of rules, hence we should handle on multiple windowed rules which there's no chance to encounter such case.

@arunmahadevan What do you think?

**Comment by HeartSaVioR** [comment]
I'd rather wait for the opinions on another approach since where to fix should be completely different between twos.

**Comment by arunmahadevan** [comment]
@HeartSaVioR , right now we will have one-one mapping between windowed rules bolt and Aggregate processor and theres no plan to support windowed rules in rules processor. So I assume you could have the "aggregate processor id-name" in the storm bolt's prefix. Will that be enough?
If you want you can look for the component name as "componentid-aggname-1-window" since theres 1-1 mapping for now.

When we support multiple windowed rules in Rule or aggregate processor we can look into it further.

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
If we don't have plan to adopt windowing to rules, why not splitting out aggregate processor from rules processor? If we just handle aggregate processor differ from rules processor, we can get rid or simplify the logic below: 
https://github.com/hortonworks/streamline/blob/master/streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/StormTopologyFluxGenerator.java#L96-L181

If we don't have plan for near future let's make it simpler. It looks like already complicated.

**Comment by arunmahadevan** [comment]
As long as the changes are not very big and restricted to the flux generation logic I am ok with the change, if it simplifies the other things like log search and metrics.

So whats your idea? Add a WindowedRuleProcessor design time entity that inherits from RulesProcessor and have a separate visit method?

**Comment by HeartSaVioR** [comment]
@arunmahadevan 
I'm thinking about having AggregateProcessor design time entity which doesn't inherit from RulesProcessor and have a separate visit method. 

Inheriting RulesProcessor should go along with some notes because of the flux generation logic. How I change the logic for test rules processor which inherits from RulesProcessor.
https://github.com/HeartSaVioR/streamline/blob/b10afba0fabc688258586b6d8a9458d5a09e41ac/streams/runners/storm/layout/src/main/java/com/hortonworks/streamline/streams/layout/storm/StormTopologyFluxGenerator.java#L169-L184

If we would still want to leverage RulesProcessor as much as possible, I could try fixing other place -  flux generation logic - to simplify the logic based on assertion that we don't have multiple windowed rules and also don't have both windowed rule and non-windowed rule. With assertions we could be safe to guess there's only one bolt which associates streamline component, and then we could name AggregateProcessor as same as others.

Either is fine, and now thinking the latter may be easier. Please let me know your thought.

**Comment by HeartSaVioR** [comment]
Just discussed briefly with @arunmahadevan and decided to go with latter approach. I'll provide the patch soon.

**Comment by HeartSaVioR** [comment]
#986
